begin;
-- Perguntas do Show do Barão (353). Gerado por barao-banco/gerar-sql.mjs; não editar à mão.
-- Rodar depois da 0066_barao_servidor.sql. Pode rodar de novo: atualiza o que mudou e apaga o que saiu.
-- A primeira alternativa de cada pergunta é a certa.
create temporary table _barao_novas (faixa int, cat text, q text, a text[]) on commit drop;
insert into _barao_novas (faixa, cat, q, a) values
  (1, 'jogo', 'Qual é o nível máximo de um campeão em uma partida?', array['18', '15', '20', '25']),
  (1, 'jogo', 'Qual empresa criou League of Legends?', array['Riot Games', 'Blizzard', 'Valve', 'Epic Games']),
  (1, 'jogo', 'Quantos jogadores tem cada time em uma partida padrão do Summoner''s Rift?', array['5', '3', '4', '6']),
  (1, 'jogo', 'Qual estrutura precisa ser destruída para vencer a partida?', array['O Nexus', 'A torre externa', 'O Barão Nashor', 'O inibidor']),
  (1, 'lore', 'Como se chama o mundo onde se passa o universo de League of Legends?', array['Runeterra', 'Azeroth', 'Tamriel', 'Midgard']),
  (1, 'lore', 'Qual série animada da Netflix se passa no universo de League of Legends?', array['Arcane', 'Castlevania', 'Cyberpunk: Edgerunners', 'Dota: Dragon''s Blood']),
  (1, 'lore', 'Em Arcane, quais são as irmãs protagonistas?', array['Vi e Jinx', 'Lux e Fiora', 'Ahri e Ashe', 'Katarina e Cassiopeia']),
  (1, 'lore', 'Qual destes campeões é de Demacia?', array['Garen', 'Darius', 'Jinx', 'Ahri']),
  (1, 'lore', 'Qual destes campeões é um yordle?', array['Teemo', 'Garen', 'Darius', 'Ashe']),
  (1, 'jogo', 'Qual é a tecla padrão da habilidade suprema (ultimate) de um campeão?', array['R', 'Q', 'F', 'T']),
  (1, 'jogo', 'Quantas habilidades ativas tem um campeão padrão?', array['4', '3', '5', '6']),
  (1, 'jogo', 'Qual é o nome do mapa principal 5 contra 5?', array['Summoner''s Rift', 'Abismo dos Lamentos', 'Floresta Retorcida', 'Mapa dos Poros']),
  (1, 'comp', 'Como se chama o campeonato mundial anual de League of Legends?', array['Worlds', 'MSI', 'All-Star', 'Rift Rivals']),
  (1, 'comp', 'Qual é o principal campeonato brasileiro de League of Legends?', array['CBLOL', 'LCK', 'LEC', 'LCS']),
  (1, 'comp', 'Faker é jogador de qual organização?', array['T1', 'G2 Esports', 'LOUD', 'Fnatic']),
  (1, 'comp', 'Em qual posição Faker joga?', array['Meio (mid)', 'Topo', 'Selva', 'Suporte']),
  (1, 'lore', 'Qual destes campeões é uma criatura do Vazio?', array['Cho''Gath', 'Garen', 'Lux', 'Ashe']),
  (1, 'lore', 'Qual campeão é famoso por plantar cogumelos explosivos?', array['Teemo', 'Ziggs', 'Heimerdinger', 'Jhin']),
  (1, 'lore', 'Qual campeã atira flechas de gelo e é a rainha dos Avarosanos?', array['Ashe', 'Caitlyn', 'Vayne', 'Varus']),
  (1, 'jogo', 'Quantos itens um campeão pode carregar no inventário principal (sem contar o totem)?', array['6', '4', '5', '8']),
  (1, 'jogo', 'Para que servem as sentinelas (wards)?', array['Dar visão do mapa', 'Curar aliados', 'Aumentar o ouro', 'Bloquear o caminho']),
  (1, 'jogo', 'Qual feitiço de invocador dá um salto curto instantâneo?', array['Flash', 'Curar', 'Barreira', 'Fantasma']),
  (1, 'comp', 'Qual país tem mais títulos mundiais de League of Legends?', array['Coreia do Sul', 'China', 'Estados Unidos', 'Brasil']),
  (1, 'jogo', 'Quantas rotas (lanes) principais existem no Summoner''s Rift?', array['3', '2', '4', '5']),
  (1, 'jogo', 'Qual é a função principal do suporte?', array['Ajudar os aliados e dar visão do mapa', 'Farmar a selva', 'Derrubar torres sozinho', 'Ficar parado na base']),
  (1, 'jogo', 'O que os lacaios (minions) concedem ao serem abatidos?', array['Ouro e experiência', 'Apenas vida', 'Itens prontos', 'Novas runas']),
  (1, 'jogo', 'Qual time começa no canto inferior esquerdo do mapa?', array['Time azul', 'Time vermelho', 'Time verde', 'Time roxo']),
  (1, 'jogo', 'O que acontece quando a vida de um campeão chega a zero?', array['Ele morre e renasce depois de um tempo', 'A partida termina', 'Ele é banido', 'Ele troca de lado']),
  (1, 'jogo', 'Qual destes é um tipo de dano no jogo?', array['Dano mágico', 'Dano elétrico', 'Dano gelado', 'Dano radioativo']),
  (1, 'jogo', 'O que significa "KDA"?', array['Abates, mortes e assistências', 'Armadura, defesa e ataque', 'Ouro, dano e abates', 'Vida, dano e armadura']),
  (1, 'jogo', 'No jogo, "CS" se refere a quê?', array['Lacaios e monstros abatidos', 'Campeões salvos', 'Chances de sorte', 'Controle de sentinelas']),
  (1, 'jogo', 'Qual modo de jogo é disputado no Abismo dos Lamentos com campeões aleatórios?', array['ARAM', 'URF', 'Arena', 'Ranqueada Flex']),
  (1, 'jogo', 'Qual modo especial deixa as recargas quase zeradas e as habilidades quase sem custo?', array['URF', 'ARAM', 'Draft Pick', 'Ranqueada Solo']),
  (1, 'jogo', 'Quantos jogadores participam, ao todo, de uma partida padrão no Summoner''s Rift?', array['10', '8', '6', '12']),
  (1, 'jogo', 'Qual estrutura ataca inimigos que se aproximam e protege a rota?', array['Torre', 'Sentinela', 'Totem', 'Altar']),
  (1, 'jogo', 'O que significa "gankar" no jargão do jogo?', array['Surpreender um inimigo vindo de outra rota', 'Comprar vários itens de uma vez', 'Derrubar o Nexus', 'Abandonar a partida']),
  (1, 'lore', 'Qual campeão é um garoto que cavalga um yeti gigante?', array['Nunu', 'Gnar', 'Volibear', 'Ornn']),
  (1, 'lore', 'Qual campeã é uma raposa de nove caudas que encanta inimigos?', array['Ahri', 'Katarina', 'Evelynn', 'Neeko']),
  (1, 'lore', 'Qual campeão é conhecido como a Mão de Noxus?', array['Darius', 'Garen', 'Draven', 'Olaf']),
  (1, 'lore', 'Qual campeão é um robô de vapor que puxa inimigos com o punho-foguete?', array['Blitzcrank', 'Orianna', 'Rammus', 'Galio']),
  (1, 'lore', 'Qual campeão é um pequeno e travesso peixe-yordle?', array['Fizz', 'Nami', 'Illaoi', 'Nautilus']),
  (1, 'lore', 'Qual campeão é um monge cego de Ionia?', array['Lee Sin', 'Yasuo', 'Wukong', 'Shen']),
  (1, 'lore', 'Qual campeão cria uma Muralha de Vento para bloquear projéteis?', array['Yasuo', 'Yone', 'Riven', 'Irelia']),
  (1, 'lore', 'Qual campeã é uma maga da Luz nascida em Demacia?', array['Lux', 'Janna', 'Soraka', 'Leona']),
  (1, 'lore', 'Qual campeã é a xerife de Piltover que usa um rifle?', array['Caitlyn', 'Vi', 'Jinx', 'Ashe']),
  (1, 'lore', 'Qual região de Runeterra é uma terra congelada de gelo e neve?', array['Freljord', 'Shurima', 'Noxus', 'Ionia']),
  (1, 'lore', 'Qual região de Runeterra é um deserto com um império antigo?', array['Shurima', 'Freljord', 'Demacia', 'Targon']),
  (1, 'lore', 'Qual cidade de Runeterra é conhecida pela tecnologia e pelo progresso?', array['Piltover', 'Zaun', 'Bilgewater', 'Noxus']),
  (1, 'lore', 'Qual cidade sombria e poluída fica sob Piltover?', array['Zaun', 'Demacia', 'Targon', 'Ixtal']),
  (1, 'lore', 'Qual império militarista é o lar de Darius, Swain e Draven?', array['Noxus', 'Demacia', 'Piltover', 'Shurima']),
  (1, 'lore', 'Em Arcane, qual personagem usa luvas gigantes que quebram paredes?', array['Vi', 'Jinx', 'Caitlyn', 'Mel']),
  (1, 'lore', 'Em Arcane, qual é o nome da cidade rica e brilhante que fica no alto?', array['Piltover', 'Zaun', 'Noxus', 'Demacia']),
  (1, 'lore', 'Em Arcane, quem é a garota de cabelos azuis e trancas compridas que adora explosões?', array['Jinx', 'Vi', 'Caitlyn', 'Mel']),
  (1, 'lore', 'Qual campeã é conhecida como "A Caída"?', array['Morgana', 'Kayle', 'Leona', 'Diana']),
  (1, 'comp', 'O que significa a sigla MSI?', array['Mid-Season Invitational', 'Major Series International', 'Master Summoner Invitational', 'Mid-Series Intercontinental']),
  (1, 'comp', 'Qual troféu é entregue ao campeão mundial de League of Legends?', array['Taça do Invocador', 'Taça do Barão', 'Troféu Nexus', 'Copa Runeterra']),
  (1, 'comp', 'A LCK é a liga profissional de qual país?', array['Coreia do Sul', 'China', 'Japão', 'Vietnã']),
  (1, 'comp', 'A LPL é a liga profissional de qual país?', array['China', 'Coreia do Sul', 'Taiwan', 'Tailândia']),
  (1, 'comp', 'A LEC é a liga profissional de qual região?', array['Europa', 'América do Norte', 'Ásia', 'Oceania']),
  (1, 'comp', 'Qual lenda sul-coreana joga no meio (mid) pela T1 e é chamada por um apelido de uma só palavra?', array['Faker', 'Chovy', 'Deft', 'Bengi']),
  (1, 'comp', 'Qual destes é um time brasileiro de League of Legends?', array['paiN Gaming', 'T1', 'Gen.G', 'G2 Esports']),
  (1, 'comp', 'O que significa a sigla CBLOL?', array['Campeonato Brasileiro de League of Legends', 'Copa Brasil de League of Legends Online', 'Circuito Brasileiro de Lutas Online', 'Campeonato Brasileiro de Liga Oficial']),
  (1, 'jogo', 'Qual destes campeões costuma jogar de atirador (ADC)?', array['Jinx', 'Garen', 'Leona', 'Lulu']),
  (1, 'jogo', 'Qual destes campeões costuma jogar de suporte?', array['Soraka', 'Zed', 'Darius', 'Jinx']),
  (1, 'jogo', 'Qual destes campeões costuma jogar na selva?', array['Lee Sin', 'Soraka', 'Lux', 'Caitlyn']),
  (1, 'jogo', 'Qual destes campeões é um assassino?', array['Zed', 'Soraka', 'Leona', 'Lux']),
  (1, 'jogo', 'Qual objetivo, ao ser derrotado, fortalece os lacaios do time?', array['Barão Nashor', 'Dragão', 'Arauto do Vale', 'Torre']),
  (1, 'lore', 'Em Arcane, quem adota Jinx e a transforma em sua "filha"?', array['Silco', 'Vander', 'Jayce', 'Singed']),
  (1, 'lore', 'Em Arcane, qual é a profissão de Caitlyn Kiramman?', array['Policial', 'Cientista', 'Conselheira', 'Ladra']),
  (1, 'lore', 'Em Arcane, quem é o amigo de infância de Jinx que mexe com o tempo?', array['Ekko', 'Jayce', 'Marcus', 'Claggor']),
  (1, 'lore', 'Qual campeão é um tatu blindado que rola em alta velocidade?', array['Rammus', 'Nasus', 'Skarner', 'Malphite']),
  (1, 'lore', 'De qual região vêm os poros, criaturas fofas e peludas?', array['Freljord', 'Ionia', 'Noxus', 'Shurima']),
  (1, 'lore', 'Qual campeão é um espantalho ancestral que aterroriza suas vítimas?', array['Fiddlesticks', 'Shaco', 'Yorick', 'Twitch']),
  (1, 'lore', 'Qual campeã é uma musicista muda de Demacia?', array['Sona', 'Lux', 'Janna', 'Karma']),
  (1, 'lore', 'Qual campeão é um cervejeiro brigão de Freljord?', array['Gragas', 'Olaf', 'Volibear', 'Braum']),
  (1, 'lore', 'Qual campeão é o rei dos trolls de Freljord?', array['Trundle', 'Sejuani', 'Gnar', 'Nunu']),
  (1, 'lore', 'Qual campeão é um cavaleiro fantasma montado em um corpo de centauro?', array['Hecarim', 'Kled', 'Pantheon', 'Sion']),
  (1, 'lore', 'Qual campeão é um minotauro de Runeterra?', array['Alistar', 'Rammus', 'Taric', 'Braum']),
  (1, 'lore', 'Qual yordle empunha um martelo gigante e vive em Demacia?', array['Poppy', 'Tristana', 'Lulu', 'Veigar']),
  (1, 'lore', 'Qual yordle pilota um robô gigante cheio de lança-chamas?', array['Rumble', 'Ziggs', 'Corki', 'Heimerdinger']),
  (1, 'lore', 'Qual yordle é especialista em explosivos e bombas Hex?', array['Ziggs', 'Teemo', 'Veigar', 'Kennen']),
  (1, 'lore', 'Qual campeão é conhecido como o Rei Macaco?', array['Wukong', 'Master Yi', 'Lee Sin', 'Sett']),
  (1, 'lore', 'Em Arcane, qual cientista tem uma doença e usa um aparelho na perna?', array['Viktor', 'Jayce', 'Singed', 'Heimerdinger']),
  (1, 'lore', 'Qual campeã de Targon empunha uma espada e um escudo solares?', array['Leona', 'Diana', 'Soraka', 'Lux']),
  (1, 'lore', 'Qual yordle é um ninja de Ionia?', array['Kennen', 'Teemo', 'Lulu', 'Tristana']),
  (1, 'lore', 'Qual campeã é uma ninja de Ionia que usa foices curtas (kama) e cortinas de fumaça?', array['Akali', 'Katarina', 'Irelia', 'Fiora']),
  (1, 'lore', 'Qual campeão é um bárbaro de Freljord que luta com dois machados?', array['Olaf', 'Darius', 'Tryndamere', 'Draven']),
  (2, 'jogo', 'Em que ano League of Legends foi lançado?', array['2009', '2006', '2011', '2013']),
  (2, 'lore', 'Qual campeã é irmã de Garen?', array['Lux', 'Fiora', 'Quinn', 'Vayne']),
  (2, 'lore', 'Qual campeão é irmão de Darius?', array['Draven', 'Swain', 'Talon', 'Sion']),
  (2, 'lore', 'Qual campeã é irmã de Morgana?', array['Kayle', 'Leona', 'Soraka', 'Diana']),
  (2, 'lore', 'Katarina é irmã de qual campeã?', array['Cassiopeia', 'LeBlanc', 'Elise', 'Camille']),
  (2, 'lore', 'Qual destes campeões é de Shurima?', array['Azir', 'Ashe', 'Karma', 'Caitlyn']),
  (2, 'lore', 'Qual destes campeões é de Freljord?', array['Tryndamere', 'Yasuo', 'Jayce', 'Nasus']),
  (2, 'lore', 'Karthus é de qual região?', array['Ilhas das Sombras', 'Ionia', 'Piltover', 'Targon']),
  (2, 'lore', 'Qual destas campeãs é de Targon?', array['Leona', 'Fiora', 'Irelia', 'Camille']),
  (2, 'lore', 'Qual destes campeões é de Zaun?', array['Warwick', 'Caitlyn', 'Garen', 'Leona']),
  (2, 'lore', 'Qual destes campeões é de Piltover?', array['Jayce', 'Darius', 'Ashe', 'Yone']),
  (2, 'lore', 'Qual destas campeãs é de Águas de Sentina (Bilgewater)?', array['Miss Fortune', 'Lux', 'Ashe', 'Soraka']),
  (2, 'lore', 'Qual destes campeões é de Noxus?', array['Swain', 'Garen', 'Tryndamere', 'Azir']),
  (2, 'lore', 'Em Arcane, qual era o nome de Jinx antes de ela se tornar Jinx?', array['Powder', 'Violet', 'Caitlyn', 'Mylo']),
  (2, 'jogo', 'Quantos dragões elementais é preciso derrotar para conquistar a Alma do Dragão?', array['4', '3', '5', '6']),
  (2, 'jogo', 'Qual modo de jogo usa o mapa Abismo dos Lamentos?', array['ARAM', 'Draft Pick', 'Ranqueada Solo', 'Arena']),
  (2, 'jogo', 'Qual runa-chave dispara dano ao acertar 3 ataques ou habilidades diferentes no mesmo alvo?', array['Eletrocutar', 'Conquistador', 'Pressione o Ataque', 'Colheita Sombria']),
  (2, 'comp', 'Qual time venceu o Worlds de 2024?', array['T1', 'Bilibili Gaming', 'Gen.G', 'G2 Esports']),
  (2, 'comp', 'Qual time venceu o Worlds de 2019, disputado em Paris?', array['FunPlus Phoenix', 'G2 Esports', 'SK Telecom T1', 'Invictus Gaming']),
  (2, 'lore', 'Como se chama a tecnologia que une magia e ciência, criada por Jayce e Viktor?', array['Hextec', 'Runatec', 'Magitec', 'Cristaltec']),
  (2, 'lore', 'Qual campeão é um dragão cósmico que forja estrelas?', array['Aurelion Sol', 'Shyvana', 'Smolder', 'Anivia']),
  (2, 'lore', 'Qual destes campeões NÃO é um yordle?', array['Garen', 'Teemo', 'Tristana', 'Lulu']),
  (2, 'lore', 'Qual destes campeões estava entre os primeiros lançados, na fase alfa do jogo?', array['Annie', 'Aphelios', 'Viego', 'Zeri']),
  (2, 'jogo', 'Qual item aumenta muito o poder de habilidade de quem o carrega?', array['Chapéu Mortal de Rabadon', 'Lâmina do Rei Destruído', 'Armadura de Espinhos', 'Botas de Mercúrio']),
  (2, 'lore', 'Qual campeão é conhecido como o rei pirata de Águas de Sentina?', array['Gangplank', 'Graves', 'Fizz', 'Nautilus']),
  (2, 'lore', 'Em Arcane, quem criou Vi e Powder depois da morte dos pais?', array['Vander', 'Silco', 'Singed', 'Jayce']),
  (2, 'comp', 'Qual time venceu o Worlds de 2023, disputado em Seul?', array['T1', 'Weibo Gaming', 'JD Gaming', 'Gen.G']),
  (2, 'jogo', 'Qual feitiço de invocador causa dano verdadeiro ao longo do tempo e reduz a cura do alvo?', array['Incendiar', 'Barreira', 'Exaustão', 'Purificar']),
  (2, 'jogo', 'Qual feitiço de invocador causa dano verdadeiro em monstros da selva?', array['Golpear', 'Flash', 'Purificar', 'Fantasma']),
  (2, 'jogo', 'Qual feitiço de invocador remove efeitos de controle de grupo do campeão?', array['Purificar', 'Curar', 'Barreira', 'Teleporte']),
  (2, 'jogo', 'Qual feitiço de invocador permite se teleportar até uma torre, lacaio ou sentinela aliada?', array['Teleporte', 'Flash', 'Fantasma', 'Exaustão']),
  (2, 'jogo', 'Qual destes é um dragão elemental do Summoner''s Rift?', array['Dragão Infernal', 'Dragão Sombrio', 'Dragão de Gelo', 'Dragão Solar']),
  (2, 'jogo', 'Qual runa acumula almas ao abater inimigos e aumenta o dano a cada alma coletada?', array['Colheita Sombria', 'Eletrocutar', 'Conquistador', 'Pressione o Ataque']),
  (2, 'jogo', 'Qual item revive o portador pouco depois de ele morrer?', array['Anjo Guardião', 'Ampulheta de Zhonya', 'Botas de Mercúrio', 'Cajado do Vazio']),
  (2, 'jogo', 'Qual item deixa o portador invulnerável, mas imóvel, por alguns segundos?', array['Ampulheta de Zhonya', 'Anjo Guardião', 'Força da Trindade', 'Gume do Infinito']),
  (2, 'jogo', 'Qual item é famoso por aumentar muito o dano de acertos críticos?', array['Gume do Infinito', 'Chapéu Mortal de Rabadon', 'Ampulheta de Zhonya', 'Anjo Guardião']),
  (2, 'jogo', 'Qual monstro do Rift pode ser capturado e usado para derrubar torres?', array['Arauto do Vale', 'Barão Nashor', 'Krug', 'Corvo']),
  (2, 'jogo', 'Qual campeã dispara uma flecha de gelo gigante que cruza o mapa e atordoa o primeiro inimigo atingido?', array['Ashe', 'Caitlyn', 'Varus', 'Vayne']),
  (2, 'jogo', 'Qual campeão tem como ultimate a "Marca da Morte"?', array['Zed', 'Talon', 'Akali', 'Kha''Zix']),
  (2, 'jogo', 'Qual campeã invoca o urso Tibbers com sua ultimate?', array['Annie', 'Lulu', 'Zyra', 'Syndra']),
  (2, 'jogo', 'Qual campeã dispara um foguete que cruza o mapa todo e causa mais dano quanto mais longe vai?', array['Jinx', 'Ziggs', 'Corki', 'Lux']),
  (2, 'jogo', 'Qual campeão tem uma lanterna que puxa aliados para perto?', array['Thresh', 'Blitzcrank', 'Pyke', 'Bard']),
  (2, 'jogo', 'Qual atirador tem um quarto disparo especial que sempre causa dano crítico?', array['Jhin', 'Ashe', 'Caitlyn', 'Varus']),
  (2, 'jogo', 'Qual campeão tem uma ultimate que atinge todos os campeões inimigos do mapa ao mesmo tempo?', array['Karthus', 'Annie', 'Lux', 'Syndra']),
  (2, 'jogo', 'Qual campeã alterna entre as formas humana e felina?', array['Nidalee', 'Neeko', 'Ahri', 'Elise']),
  (2, 'jogo', 'Qual campeã alterna entre a forma humana e a de aranha?', array['Elise', 'Nidalee', 'Cassiopeia', 'Lissandra']),
  (2, 'jogo', 'Qual campeão é formado por dois espíritos, um lobo e um cordeiro?', array['Kindred', 'Kalista', 'Yorick', 'Hecarim']),
  (2, 'lore', 'Qual destes campeões é de Ionia?', array['Ahri', 'Lux', 'Jinx', 'Garen']),
  (2, 'lore', 'Qual destes campeões vem de Bandle City, a terra dos yordles?', array['Lulu', 'Garen', 'Ashe', 'Jinx']),
  (2, 'lore', 'Qual destes campeões é das Ilhas das Sombras?', array['Thresh', 'Jayce', 'Nasus', 'Ahri']),
  (2, 'lore', 'Qual campeã de Noxus é uma assassina de cabelos ruivos que usa adagas?', array['Katarina', 'Talon', 'Draven', 'LeBlanc']),
  (2, 'lore', 'Qual campeão de Piltover usa um martelo Hextec que muda de forma?', array['Jayce', 'Vi', 'Caitlyn', 'Ezreal']),
  (2, 'lore', 'Qual campeão é um explorador de Piltover que usa uma luva arcana?', array['Ezreal', 'Jayce', 'Corki', 'Lucian']),
  (2, 'lore', 'Qual campeão do Vazio é um olho gigante que dispara raios?', array['Vel''Koz', 'Kha''Zix', 'Cho''Gath', 'Rek''Sai']),
  (2, 'lore', 'Qual campeão do Vazio é um predador que evolui as próprias garras?', array['Kha''Zix', 'Cho''Gath', 'Vel''Koz', 'Kog''Maw']),
  (2, 'lore', 'Em Arcane, quem é o dono do bar "The Last Drop"?', array['Vander', 'Silco', 'Jayce', 'Ekko']),
  (2, 'lore', 'Em Arcane, como se chama a substância roxa que dá força e corrói quem a usa?', array['Shimmer', 'Hextec', 'Tônico', 'Névoa Negra']),
  (2, 'lore', 'Em Arcane, qual é o sobrenome de Caitlyn?', array['Kiramman', 'Medarda', 'Talis', 'Lorcan']),
  (2, 'lore', 'Qual campeão é irmão de Yasuo?', array['Yone', 'Zed', 'Shen', 'Kayn']),
  (2, 'lore', 'Qual destes campeões NÃO é de Noxus?', array['Lux', 'Darius', 'Katarina', 'Draven']),
  (2, 'lore', 'Qual campeã é de Ixtal, a terra dos elementos?', array['Qiyana', 'Samira', 'Ahri', 'Fiora']),
  (2, 'lore', 'Qual campeã é considerada a maior duelista de Demacia?', array['Fiora', 'Lux', 'Quinn', 'Sona']),
  (2, 'lore', 'Qual campeão é o príncipe de Demacia?', array['Jarvan IV', 'Garen', 'Galio', 'Xin Zhao']),
  (2, 'lore', 'Qual campeão canaliza os espíritos do Tigre, da Tartaruga, do Urso e da Fênix?', array['Udyr', 'Volibear', 'Olaf', 'Sejuani']),
  (2, 'lore', 'Qual yordle se intitula o Mestre do Mal?', array['Veigar', 'Teemo', 'Ziggs', 'Rumble']),
  (2, 'lore', 'Qual campeão é um colosso de pedra criado em Demacia para combater magos?', array['Galio', 'Malphite', 'Taric', 'Rammus']),
  (2, 'lore', 'Qual campeão é um Ascendido de Shurima?', array['Nasus', 'Garen', 'Karma', 'Lux']),
  (2, 'lore', 'Qual destes campeões é um Darkin?', array['Aatrox', 'Garen', 'Jhin', 'Lucian']),
  (2, 'lore', 'Em Arcane, qual é a relação entre Ambessa Medarda e Mel?', array['Mãe e filha', 'Irmãs', 'Tia e sobrinha', 'Avó e neta']),
  (2, 'lore', 'Em Arcane, quem é o braço direito de Silco, com um braço mecânico?', array['Sevika', 'Mel', 'Ekko', 'Vi']),
  (2, 'lore', 'Twisted Fate é de qual região de Runeterra?', array['Águas de Sentina', 'Noxus', 'Piltover', 'Demacia']),
  (2, 'lore', 'Segundo o universo do jogo, de onde vem o Barão Nashor?', array['Do Vazio', 'De Shurima', 'Das Ilhas das Sombras', 'De Zaun']),
  (2, 'lore', 'Diana, de Targon, é associada a qual astro?', array['Lua', 'Sol', 'Cometas', 'Estrelas cadentes']),
  (2, 'lore', 'Qual campeão é conhecido como o Titã das Profundezas?', array['Nautilus', 'Fizz', 'Illaoi', 'Pyke']),
  (2, 'comp', 'Qual jogador da T1, campeã mundial de 2023, joga de suporte?', array['Keria', 'Gumayusi', 'Zeus', 'Oner']),
  (2, 'comp', 'Qual jogador da T1, campeã mundial de 2023, joga de atirador (ADC)?', array['Gumayusi', 'Keria', 'Zeus', 'Faker']),
  (2, 'comp', 'Qual jogador da T1, campeã mundial de 2023, joga na selva?', array['Oner', 'Keria', 'Zeus', 'Gumayusi']),
  (2, 'comp', 'Qual jogador da T1, campeã mundial de 2023, joga no topo?', array['Zeus', 'Oner', 'Faker', 'Keria']),
  (2, 'comp', 'Chovy, famoso jogador sul-coreano, joga em qual posição?', array['Meio (mid)', 'Topo', 'Selva', 'Suporte']),
  (2, 'comp', 'Caps e Perkz ficaram famosos por qual time europeu?', array['G2 Esports', 'Fnatic', 'Origen', 'Misfits']),
  (2, 'comp', 'Em que ano foi disputado o primeiro Worlds?', array['2011', '2009', '2010', '2012']),
  (2, 'comp', 'FunPlus Phoenix, campeão mundial de 2019, é de qual país?', array['China', 'Coreia do Sul', 'Taiwan', 'Estados Unidos']),
  (2, 'comp', 'DRX, campeão mundial de 2022, é de qual país?', array['Coreia do Sul', 'China', 'Vietnã', 'Japão']),
  (2, 'comp', 'Bjergsen é um jogador famoso por qual posição?', array['Meio (mid)', 'Topo', 'Selva', 'Suporte']),
  (2, 'jogo', 'Qual feitiço de invocador aumenta a velocidade de movimento e permite atravessar unidades?', array['Fantasma', 'Flash', 'Purificar', 'Barreira']),
  (2, 'jogo', 'Qual feitiço de invocador reduz a velocidade e o dano do alvo?', array['Exaustão', 'Incendiar', 'Curar', 'Golpear']),
  (2, 'jogo', 'Qual feitiço de invocador cria um escudo temporário no campeão?', array['Barreira', 'Curar', 'Exaustão', 'Teleporte']),
  (2, 'jogo', 'Qual item do totem revela e desativa sentinelas inimigas?', array['Lente do Oráculo', 'Sentinela de Controle', 'Totem de Visão', 'Olho de Herald']),
  (2, 'jogo', 'Qual campeão é um rato da Zaun que fica invisível e usa uma besta?', array['Twitch', 'Teemo', 'Rengar', 'Singed']),
  (2, 'jogo', 'Qual campeão manipula o próprio sangue e é um vampiro de Noxus?', array['Vladimir', 'Swain', 'Evelynn', 'Draven']),
  (2, 'jogo', 'Qual campeão é um alquimista de Zaun que deixa um rastro de veneno por onde passa?', array['Singed', 'Dr. Mundo', 'Viktor', 'Warwick']),
  (2, 'jogo', 'Qual campeão é um bandido de Bilgewater que usa uma espingarda de cano duplo?', array['Graves', 'Twisted Fate', 'Gangplank', 'Draven']),
  (2, 'jogo', 'Qual suporte de Bilgewater usa um gancho e foi dado como morto?', array['Pyke', 'Nautilus', 'Thresh', 'Bard']),
  (2, 'lore', 'Qual campeão é de Targon e usa armas lunares?', array['Aphelios', 'Jhin', 'Varus', 'Kai''Sa']),
  (2, 'lore', 'Qual bruxa de gelo vive em Freljord?', array['Lissandra', 'Ashe', 'Anivia', 'Sejuani']),
  (2, 'lore', 'Qual líder noxiano é o Grande General de Noxus, acompanhado de um corvo?', array['Swain', 'Darius', 'Draven', 'Singed']),
  (2, 'lore', 'Qual é a montanha mais alta de Runeterra?', array['Monte Targon', 'Monte Ionia', 'Pico Frio', 'Monte Shurima']),
  (2, 'lore', 'Aatrox foi derrotado e aprisionado após qual conflito?', array['Guerra Darkin', 'Guerra Rúnica', 'Guerra do Vazio', 'Guerra Noxiana']),
  (2, 'lore', 'Qual destes campeões é de Águas de Sentina (Bilgewater)?', array['Gangplank', 'Ashe', 'Soraka', 'Lux']),
  (2, 'lore', 'Qual campeã é irmã de Jinx?', array['Vi', 'Caitlyn', 'Lux', 'Katarina']),
  (2, 'lore', 'Qual é o sobrenome de Garen e Lux?', array['Crownguard', 'Lightshield', 'Du Couteau', 'Kiramman']),
  (2, 'lore', 'Qual campeão é casado com Ashe, a rainha dos Avarosanos?', array['Tryndamere', 'Olaf', 'Braum', 'Volibear']),
  (2, 'lore', 'Qual campeão é conhecido como o Coração de Freljord, de grande escudo e bigode?', array['Braum', 'Gragas', 'Trundle', 'Ornn']),
  (2, 'lore', 'Qual campeã liderou a resistência de Ionia contra a invasão de Noxus?', array['Irelia', 'Karma', 'Akali', 'Lux']),
  (2, 'lore', 'Qual império invadiu Ionia e deixou cicatrizes na região?', array['Noxus', 'Demacia', 'Piltover', 'Shurima']),
  (2, 'lore', 'Qual campeã é uma Vastaya rebelde de Ionia que usa penas como armas?', array['Xayah', 'Ahri', 'Neeko', 'Sivir']),
  (2, 'lore', 'Qual campeã, chamada de Rosa do Deserto, nasceu em Shurima?', array['Samira', 'Sivir', 'Qiyana', 'Nidalee']),
  (2, 'lore', 'A qual ordem de Targon pertence Leona?', array['Solari', 'Lunari', 'Kinkou', 'Piltover']),
  (2, 'lore', 'Qual campeã é um demônio que se alimenta da dor de suas vítimas?', array['Evelynn', 'Morgana', 'Elise', 'Zyra']),
  (2, 'lore', 'Qual campeão é conhecido como o Pesadelo Eterno?', array['Nocturne', 'Fiddlesticks', 'Shaco', 'Mordekaiser']),
  (2, 'lore', 'Qual campeão é um andarilho cósmico que coleta sinos (chimes)?', array['Bard', 'Aurelion Sol', 'Zilean', 'Taric']),
  (2, 'lore', 'Qual Ascendido de Shurima é um mago de energia arcana preso em um sarcófago?', array['Xerath', 'Azir', 'Nasus', 'Renekton']),
  (2, 'lore', 'Qual campeã demaciana luta ao lado de uma águia chamada Valor?', array['Quinn', 'Vayne', 'Fiora', 'Sona']),
  (2, 'lore', 'Qual campeã é uma Marai, criatura do mar?', array['Nami', 'Soraka', 'Illaoi', 'Karma']),
  (2, 'lore', 'Qual campeã é a Imperatriz do Vazio?', array['Bel''Veth', 'Vel''Koz', 'Rek''Sai', 'Cho''Gath']),
  (2, 'lore', 'Qual campeão é conhecido como o Andarilho do Vazio?', array['Kassadin', 'Malzahar', 'Kha''Zix', 'Vel''Koz']),
  (2, 'lore', 'Como são chamados os líderes criminosos que dominam Zaun?', array['Barões Químicos', 'Conselheiros', 'Senhores da Névoa', 'Capitães do Bilge']),
  (2, 'lore', 'Qual campeã é uma cantora pop de Piltover?', array['Seraphine', 'Sona', 'Karma', 'Janna']),
  (2, 'lore', 'Qual campeã de Piltover tem pernas blindadas e lâminas retráteis?', array['Camille', 'Fiora', 'Irelia', 'Katarina']),
  (2, 'lore', 'Qual yordle pré-histórico foi descongelado em Freljord?', array['Gnar', 'Kled', 'Poppy', 'Rumble']),
  (3, 'comp', 'Qual time venceu o primeiro Worlds, em 2011?', array['Fnatic', 'Taipei Assassins', 'SK Telecom T1', 'Against All authority']),
  (3, 'comp', 'De qual região era o Taipei Assassins, campeão mundial de 2012?', array['Taiwan', 'Coreia do Sul', 'China', 'América do Norte']),
  (3, 'comp', 'Qual time venceu o Worlds de 2020, disputado em Xangai?', array['DAMWON Gaming', 'Suning', 'G2 Esports', 'Top Esports']),
  (3, 'comp', 'Qual time venceu o Worlds de 2021, disputado em Reykjavik?', array['Edward Gaming', 'DWG KIA', 'T1', 'Cloud9']),
  (3, 'comp', 'Qual time venceu o Worlds de 2022, em San Francisco?', array['DRX', 'T1', 'JD Gaming', 'Gen.G']),
  (3, 'comp', 'Qual time venceu o Worlds de 2018, disputado na Coreia do Sul?', array['Invictus Gaming', 'Fnatic', 'G2 Esports', 'Cloud9']),
  (3, 'comp', 'Qual time europeu foi vice-campeão do Worlds de 2019?', array['G2 Esports', 'Fnatic', 'Origen', 'Misfits']),
  (3, 'comp', 'Em qual posição jogava Uzi, lenda chinesa do League of Legends?', array['Atirador (ADC)', 'Topo', 'Selva', 'Meio (mid)']),
  (3, 'comp', 'Qual time venceu o Worlds de 2017, disputado em Pequim?', array['Samsung Galaxy', 'SK Telecom T1', 'Royal Never Give Up', 'Misfits']),
  (3, 'lore', 'Qual rei perdeu a amada rainha Isolde e criou a Névoa Negra?', array['Viego', 'Mordekaiser', 'Swain', 'Jarvan III']),
  (3, 'lore', 'Qual ordem ionia, de Shen e Kennen, mantém o equilíbrio entre os mundos?', array['Kinkou', 'Ordem das Sombras', 'Guarda Crownguard', 'Vigilantes']),
  (3, 'lore', 'Qual campeão ergueu o Disco Solar e restaurou Shurima?', array['Azir', 'Nasus', 'Renekton', 'Xerath']),
  (3, 'lore', 'Quem é o grande vilão de Zaun na primeira temporada de Arcane?', array['Silco', 'Vander', 'Singed', 'Heimerdinger']),
  (3, 'lore', 'Qual yordle é Conselheiro de Piltover em Arcane?', array['Heimerdinger', 'Teemo', 'Tristana', 'Ziggs']),
  (3, 'comp', 'Em qual cidade foi disputada a final do Worlds de 2023?', array['Seul', 'Paris', 'Londres', 'Xangai']),
  (3, 'comp', 'Em qual cidade foi disputada a final do Worlds de 2024?', array['Londres', 'Seul', 'Paris', 'Berlim']),
  (3, 'comp', 'Em que ano Faker conquistou o seu primeiro título mundial?', array['2013', '2011', '2015', '2016']),
  (3, 'comp', 'Qual time venceu o Worlds de 2016, em Los Angeles?', array['SK Telecom T1', 'Samsung Galaxy', 'Royal Never Give Up', 'ROX Tigers']),
  (3, 'comp', 'Qual time venceu o Worlds de 2015, disputado em Berlim?', array['SK Telecom T1', 'KOO Tigers', 'Origen', 'Fnatic']),
  (3, 'lore', 'Em Arcane, qual conselheira de Piltover tem origem noxiana?', array['Mel Medarda', 'Ambessa Medarda', 'Caitlyn Kiramman', 'Sevika']),
  (3, 'lore', 'Qual é o título de Viego?', array['O Rei Arruinado', 'O Rei Caído', 'O Rei das Sombras', 'O Rei Esquecido']),
  (3, 'lore', 'Em Arcane, quem transforma Vander no monstro Warwick?', array['Singed', 'Silco', 'Jayce', 'Viktor']),
  (3, 'comp', 'Qual time venceu o primeiro MSI da história, em 2015?', array['Edward Gaming', 'SK Telecom T1', 'Fnatic', 'KOO Tigers']),
  (3, 'comp', 'Qual time venceu o MSI de 2016, disputado em Xangai?', array['SK Telecom T1', 'Counter Logic Gaming', 'G2 Esports', 'Flash Wolves']),
  (3, 'comp', 'Em qual país foi disputado o MSI de 2017?', array['Brasil', 'Coreia do Sul', 'França', 'Estados Unidos']),
  (3, 'comp', 'Qual time europeu conquistou o MSI de 2019?', array['G2 Esports', 'Fnatic', 'Origen', 'Splyce']),
  (3, 'comp', 'Qual time venceu o Worlds de 2014 em Seul?', array['Samsung White', 'Star Horn Royal Club', 'Taipei Assassins', 'OMG']),
  (3, 'comp', 'Qual time foi vice-campeão do Worlds de 2018?', array['Fnatic', 'G2 Esports', 'Cloud9', 'Royal Never Give Up']),
  (3, 'comp', 'Qual time foi vice-campeão do Worlds de 2015?', array['KOO Tigers', 'Fnatic', 'Origen', 'Samsung White']),
  (3, 'comp', 'Qual time derrotou o SK Telecom T1 na final do Worlds de 2017?', array['Samsung Galaxy', 'Royal Never Give Up', 'Misfits', 'Longzhu Gaming']),
  (3, 'comp', 'Qual time foi vice-campeão do Worlds de 2020?', array['Suning', 'Top Esports', 'JD Gaming', 'G2 Esports']),
  (3, 'comp', 'Qual time foi vice-campeão do Worlds de 2021?', array['DWG KIA', 'T1', 'Cloud9', 'Gen.G']),
  (3, 'comp', 'Qual time foi vice-campeão do Worlds de 2022?', array['T1', 'DRX', 'JD Gaming', 'G2 Esports']),
  (3, 'comp', 'Qual time foi vice-campeão do Worlds de 2023?', array['Weibo Gaming', 'JD Gaming', 'Gen.G', 'Bilibili Gaming']),
  (3, 'comp', 'Qual time foi vice-campeão do Worlds de 2024?', array['Bilibili Gaming', 'Gen.G', 'Top Esports', 'Fnatic']),
  (3, 'comp', 'Qual jogador de meio foi destaque do DAMWON Gaming, campeão mundial de 2020?', array['ShowMaker', 'Faker', 'Chovy', 'Bdd']),
  (3, 'comp', 'De qual fase o DRX partiu para conquistar o Worlds de 2022?', array['Da fase de entrada (Play-In)', 'Das quartas de final', 'Da fase suíça', 'Das semifinais']),
  (3, 'comp', 'Qual formato inédito foi usado na fase de grupos do Worlds de 2023?', array['Sistema suíço', 'Dupla eliminação', 'Pontos corridos', 'Grupos de seis times']),
  (3, 'comp', 'Jankos, lendário jogador de G2, atua em qual posição?', array['Selva', 'Topo', 'Meio (mid)', 'Suporte']),
  (3, 'comp', 'Doublelift ficou famoso no cenário norte-americano em qual posição?', array['Atirador (ADC)', 'Topo', 'Selva', 'Suporte']),
  (3, 'comp', 'Caps, estrela de G2, é de qual país?', array['Dinamarca', 'Suécia', 'Alemanha', 'França']),
  (3, 'comp', 'Rekkles, conhecido atirador europeu, é de qual país?', array['Suécia', 'Dinamarca', 'Polônia', 'Espanha']),
  (3, 'comp', 'Jankos, conhecido selvagem europeu, é de qual país?', array['Polônia', 'Alemanha', 'Croácia', 'Itália']),
  (3, 'comp', 'Uzi, lenda do LoL, jogou em qual cenário?', array['Chinês (LPL)', 'Coreano (LCK)', 'Europeu (LEC)', 'Brasileiro (CBLOL)']),
  (3, 'comp', 'Em que ano ocorreu a primeira temporada (Season 1) competitiva de LoL?', array['2011', '2009', '2013', '2015']),
  (3, 'jogo', 'Qual campeão coleta almas dos inimigos para aumentar seu poder?', array['Thresh', 'Karthus', 'Mordekaiser', 'Nami']),
  (3, 'jogo', 'Qual campeão usa duas armas por vez, escolhendo entre cinco tipos diferentes?', array['Aphelios', 'Jhin', 'Kai''Sa', 'Varus']),
  (3, 'jogo', 'Qual campeã ganha invulnerabilidade com a ultimate Intervenção (para ela ou um aliado)?', array['Kayle', 'Lulu', 'Taric', 'Leona']),
  (3, 'jogo', 'Qual campeã pode curar todos os aliados do mapa com a ultimate?', array['Soraka', 'Sona', 'Janna', 'Nami']),
  (3, 'jogo', 'Qual campeão manipula o tempo com bombas e pode reviver um aliado com a ultimate?', array['Zilean', 'Ekko', 'Taric', 'Bard']),
  (3, 'jogo', 'Qual campeão se transforma em uma versão gigante quando enraivecido?', array['Gnar', 'Nasus', 'Renekton', 'Sion']),
  (3, 'jogo', 'Qual item é especialmente eficaz contra inimigos com muita resistência mágica, por penetrar resistência?', array['Cajado do Vazio', 'Lembrete Mortal', 'Armadura de Espinhos', 'Botas de Mercúrio']),
  (3, 'jogo', 'Qual item diminui a duração de efeitos de controle de grupo?', array['Botas de Mercúrio', 'Botas de Mobilidade', 'Botas de Feiticeiro', 'Botas de Berserker']),
  (3, 'jogo', 'Qual item causa lentidão ao dar dano com habilidades?', array['Cetro de Cristal de Rylai', 'Gume do Infinito', 'Anjo Guardião', 'Lembrete Mortal']),
  (3, 'lore', 'Qual campeão forjou estrelas e é um dragão cósmico?', array['Aurelion Sol', 'Shyvana', 'Smolder', 'Anivia']),
  (3, 'lore', 'Qual campeã é uma fênix de gelo?', array['Anivia', 'Brand', 'Lissandra', 'Ashe']),
  (3, 'lore', 'Qual campeão é meio dragão e meio humano?', array['Shyvana', 'Aurelion Sol', 'Smolder', 'Heimerdinger']),
  (3, 'lore', 'Qual campeão é um lobisomem criado em Zaun?', array['Warwick', 'Nasus', 'Gnar', 'Volibear']),
  (3, 'jogo', 'Qual item combina penetração de armadura e redução de cura?', array['Lembrete Mortal', 'Anjo Guardião', 'Ampulheta de Zhonya', 'Cetro de Cristal de Rylai']),
  (3, 'jogo', 'A runa Eletrocutar pertence a qual árvore de runas?', array['Dominação', 'Precisão', 'Feitiçaria', 'Determinação']),
  (3, 'jogo', 'A runa Conquistador pertence a qual árvore de runas?', array['Precisão', 'Dominação', 'Feitiçaria', 'Inspiração']),
  (3, 'jogo', 'Qual campeão continua lançando habilidades por alguns segundos depois de morrer?', array['Karthus', 'Mordekaiser', 'Yorick', 'Kayn']),
  (3, 'jogo', 'Qual campeão pode se tornar Rhaast ou a Sombra Assassina?', array['Kayn', 'Zed', 'Talon', 'Akali']),
  (3, 'jogo', 'Qual campeão ganha ouro com a passiva "Adoração" ao pegar machados giratórios?', array['Draven', 'Darius', 'Olaf', 'Tryndamere']),
  (3, 'jogo', 'Qual campeão invoca caixas-surpresa que assustam os inimigos?', array['Shaco', 'Fiddlesticks', 'Teemo', 'Zyra']),
  (3, 'jogo', 'Qual campeão detona barris de pólvora para causar dano em área?', array['Gangplank', 'Graves', 'Twisted Fate', 'Nautilus']),
  (3, 'jogo', 'Qual mapa clássico do jogo era disputado em 3 contra 3?', array['Floresta Retorcida', 'Abismo dos Lamentos', 'Summoner''s Rift', 'Cristal Ardente']),
  (3, 'jogo', 'Em quais níveis o campeão pode aprender ou melhorar a ultimate?', array['6, 11 e 16', '5, 10 e 15', '6, 12 e 18', '4, 8 e 12']),
  (3, 'jogo', 'Qual é o nível máximo de uma habilidade básica (Q, W ou E) de um campeão comum?', array['5', '3', '4', '6']),
  (3, 'jogo', 'Quantos inibidores cada time tem na base?', array['3', '2', '4', '5']),
  (3, 'lore', 'Viego foi rei de qual antigo reino?', array['Camavor', 'Demacia', 'Shurima', 'Ixtal']),
  (3, 'lore', 'Qual campeão é conhecido como o Rei Bárbaro?', array['Tryndamere', 'Olaf', 'Sejuani', 'Volibear']),
  (3, 'lore', 'Qual campeã demaciana caça criaturas das trevas com uma besta?', array['Vayne', 'Quinn', 'Fiora', 'Lux']),
  (3, 'lore', 'Qual campeão se apresenta como "Dr." e vem de Zaun?', array['Dr. Mundo', 'Warwick', 'Viktor', 'Jayce']),
  (3, 'lore', 'Qual profeta do Vazio é um mago de Shurima que comanda criaturas do Vazio?', array['Malzahar', 'Kassadin', 'Cho''Gath', 'Vel''Koz']),
  (3, 'lore', 'Qual campeão é um mago preso em Demacia que usa correntes e rouba magias?', array['Sylas', 'Lucian', 'Garen', 'Galio']),
  (3, 'lore', 'Qual campeã humana de Shurima carrega uma armadura do Vazio?', array['Kai''Sa', 'Samira', 'Sivir', 'Nami']),
  (3, 'lore', 'Zeri é de qual cidade?', array['Zaun', 'Piltover', 'Noxus', 'Bilgewater']),
  (3, 'lore', 'Qual campeã é uma autômata de relojoaria criada em Piltover?', array['Orianna', 'Camille', 'Janna', 'Taliyah']),
  (3, 'lore', 'Como se chama o continente de Runeterra onde ficam Demacia, Noxus e Freljord?', array['Valoran', 'Targon', 'Shurima', 'Ixtal']),
  (3, 'lore', 'Qual instituição regula as batalhas da Liga em Valoran?', array['Instituto de Guerra', 'Conselho de Piltover', 'Ordem dos Magos', 'Guarda Ocidental']),
  (3, 'lore', 'Como são chamados, no universo do jogo, os campos de batalha onde os campeões lutam?', array['Campos da Justiça', 'Campos da Glória', 'Arenas do Barão', 'Planícies do Vazio']),
  (3, 'lore', 'Qual é o sobrenome de Jayce em Arcane?', array['Talis', 'Kiramman', 'Medarda', 'Lorcan']),
  (3, 'lore', 'Qual banda virtual de heavy metal reúne Mordekaiser, Karthus, Sona, Yorick, Olaf e Kayle?', array['Pentakill', 'K/DA', 'True Damage', 'Heartsteel']),
  (3, 'lore', 'Qual grupo virtual de K-pop reúne Ahri, Akali, Evelynn e Kai''Sa?', array['K/DA', 'Pentakill', 'True Damage', 'Heartsteel']),
  (3, 'lore', 'Qual grupo virtual de hip-hop reúne Senna, Yasuo, Ekko, Qiyana e Akali?', array['True Damage', 'K/DA', 'Pentakill', 'Heartsteel']),
  (3, 'lore', 'Qual boy band virtual reúne Aphelios, Ezreal, Sett, Yone e K''Sante?', array['Heartsteel', 'K/DA', 'Pentakill', 'True Damage']),
  (3, 'comp', 'Qual time chinês foi derrotado pelo SK Telecom T1 na final do Worlds de 2013?', array['Royal Club', 'Oh My God', 'Edward Gaming', 'Invictus Gaming']),
  (3, 'comp', 'Qual time foi vice-campeão do Worlds de 2012, perdendo para o Taipei Assassins?', array['Azubu Frost', 'Fnatic', 'Moscow Five', 'Counter Logic Gaming']),
  (3, 'jogo', 'Qual campeão salta do céu e causa dano em área com a ultimate (Grande Cometa)?', array['Pantheon', 'Leona', 'Diana', 'Taric']),
  (3, 'lore', 'Qual campeão tem cabeça de chacal e é um Ascendido de Shurima?', array['Nasus', 'Renekton', 'Azir', 'Xerath']),
  (3, 'lore', 'Qual campeão tem forma de crocodilo e é um Ascendido de Shurima?', array['Renekton', 'Nasus', 'Azir', 'Xerath']),
  (3, 'lore', 'Qual campeã é uma planta viva que domina espinhos e raízes?', array['Zyra', 'Maokai', 'Neeko', 'Ivern']),
  (3, 'lore', 'Qual campeão é uma árvore antiga, tomada por magia sombria, que protege a floresta?', array['Maokai', 'Ivern', 'Zyra', 'Neeko']),
  (3, 'lore', 'Qual campeão é um golem de pedra, do tamanho de uma montanha, que lança rochas?', array['Malphite', 'Galio', 'Rammus', 'Taric']),
  (3, 'lore', 'Qual é o sobrenome da família de Katarina e Cassiopeia?', array['Du Couteau', 'Crownguard', 'Medarda', 'Darkwill']),
  (3, 'lore', 'Qual campeão é conhecido como o Olho do Crepúsculo?', array['Shen', 'Kennen', 'Zed', 'Akali']),
  (3, 'lore', 'Qual campeã é o Aspecto do Crepúsculo, de Targon?', array['Zoe', 'Soraka', 'Diana', 'Leona']),
  (3, 'lore', 'Qual campeão é casado com Senna?', array['Lucian', 'Jhin', 'Graves', 'Ezreal']),
  (3, 'lore', 'Qual campeão é conhecido como o Escudo de Valoran?', array['Taric', 'Braum', 'Galio', 'Garen']),
  (3, 'lore', 'Qual campeão é um demônio conhecido como o Rei do Rio?', array['Tahm Kench', 'Nautilus', 'Fizz', 'Pyke']),
  (3, 'lore', 'Qual campeão noxiano foi um herói ressuscitado como um colosso morto-vivo?', array['Sion', 'Mordekaiser', 'Darius', 'Swain']),
  (3, 'lore', 'Qual campeão se considera um artista e é chamado de Virtuoso?', array['Jhin', 'Zed', 'Shaco', 'Kayn']),
  (3, 'lore', 'Qual campeã é sacerdotisa de Nagakabouros, deus do mar de Águas de Sentina?', array['Illaoi', 'Nami', 'Miss Fortune', 'Karma']),
  (3, 'lore', 'De qual antiga cidade, destruída pelo Vazio, vem Zilean?', array['Icathia', 'Shurima', 'Camavor', 'Ixtal']),
  (3, 'lore', 'Qual campeã Darkin é uma matilha de cães, cada um com uma parte da lâmina?', array['Naafiri', 'Aatrox', 'Varus', 'Kayn']),
  (3, 'lore', 'Qual arqueiro de Ionia foi fundido a um Darkin?', array['Varus', 'Jhin', 'Ashe', 'Kindred']),
  (3, 'lore', 'Qual campeão de Targon é um guerreiro cujo manto passa a outro mortal quando ele morre?', array['Pantheon', 'Leona', 'Taric', 'Aphelios']),
  (3, 'lore', 'Qual campeã é uma camaleoa Vastaya de Ixtal que muda de forma?', array['Neeko', 'Qiyana', 'Ahri', 'Zyra']),
  (3, 'lore', 'Qual yordle cavalga o lagarto Skaarl?', array['Kled', 'Gnar', 'Rumble', 'Poppy']),
  (3, 'lore', 'Qual campeão do Vazio é conhecido como a Boca do Abismo?', array['Kog''Maw', 'Cho''Gath', 'Kha''Zix', 'Vel''Koz']),
  (3, 'lore', 'Qual banda canta "Enemy", tema de abertura de Arcane, ao lado do rapper J.I.D?', array['Imagine Dragons', 'Coldplay', 'Linkin Park', 'Twenty One Pilots']),
  (4, 'comp', 'Em qual cidade da Suécia foi decidido o Worlds de 2011?', array['Jönköping', 'Estocolmo', 'Gotemburgo', 'Malmö']),
  (4, 'comp', 'Qual foi o placar da final do Worlds de 2022, entre DRX e T1?', array['3 a 2', '3 a 0', '3 a 1', '2 a 1']),
  (4, 'comp', 'Qual foi o placar da final do Worlds de 2020, entre DAMWON Gaming e Suning?', array['3 a 1', '3 a 0', '3 a 2', '2 a 1']),
  (4, 'comp', 'Em qual cidade sul-coreana foi disputada a final do Worlds de 2018?', array['Incheon', 'Seul', 'Busan', 'Daegu']),
  (4, 'comp', 'Em qual estádio de Pequim foi disputada a final do Worlds de 2017?', array['Ninho de Pássaro (Estádio Nacional)', 'Cubo d''Água', 'Workers'' Stadium', 'Ginásio Capital']),
  (4, 'comp', 'Quantos títulos mundiais a SK Telecom T1 conquistou antes de virar apenas T1?', array['3', '2', '4', '5']),
  (4, 'comp', 'Em que ano a Riot Games foi fundada?', array['2006', '2004', '2008', '2009']),
  (4, 'comp', 'Em que data League of Legends foi lançado oficialmente?', array['27 de outubro de 2009', '10 de abril de 2009', '1º de janeiro de 2010', '9 de setembro de 2011']),
  (4, 'lore', 'Quem fundou a Riot Games?', array['Brandon Beck e Marc Merrill', 'Mike Morhaime e Frank Pearce', 'Gabe Newell e Erik Johnson', 'Jeff Kaplan e Rob Pardo']),
  (4, 'lore', 'Em Arcane, quais são os dois amigos de infância de Vi que participam do assalto do primeiro episódio?', array['Mylo e Claggor', 'Ekko e Benzo', 'Deckard e Marcus', 'Sky e Finn']),
  (4, 'jogo', 'Quantas torres cada time possui no Summoner''s Rift, contando as do Nexus?', array['11', '9', '10', '12']),
  (4, 'comp', 'Quantos títulos do MSI o Royal Never Give Up conquistou entre 2018 e 2022?', array['3', '2', '1', '4']),
  (4, 'comp', 'Em qual país foi disputado o primeiro MSI, em 2015?', array['Estônia', 'China', 'Brasil', 'França']),
  (4, 'comp', 'Em qual cidade foi disputado o MSI de 2022?', array['Busan', 'Seul', 'Xangai', 'Daegu']),
  (4, 'comp', 'Em qual cidade foi disputado o MSI de 2023?', array['Londres', 'Seul', 'Paris', 'Berlim']),
  (4, 'comp', 'Em qual cidade da China foi disputado o MSI de 2024?', array['Chengdu', 'Xangai', 'Pequim', 'Shenzhen']),
  (4, 'comp', 'Em qual cidade dos EUA foi disputada a final do Worlds de 2013?', array['Los Angeles', 'Nova York', 'Chicago', 'Las Vegas']),
  (4, 'jogo', 'Quanto ouro cada jogador tem no início de uma partida no Summoner''s Rift?', array['500', '475', '625', '1000']),
  (4, 'jogo', 'Quantos tipos de dragão elemental existem hoje no Summoner''s Rift, contando Hextec e Químico?', array['6', '4', '5', '8']),
  (4, 'jogo', 'Em qual ano foi lançado o campeão Yasuo?', array['2013', '2011', '2015', '2017']),
  (4, 'jogo', 'Em qual ano foi lançado o campeão Aphelios?', array['2019', '2017', '2021', '2015']),
  (4, 'jogo', 'Em qual ano foi lançado o campeão Viego?', array['2021', '2019', '2023', '2017']),
  (4, 'lore', 'Os fundadores da Riot, Brandon Beck e Marc Merrill, usam apelidos de campeões. Quais?', array['Ryze e Tryndamere', 'Teemo e Garen', 'Ashe e Darius', 'Annie e Zilean']),
  (4, 'lore', 'Qual é o nome do Imperador de Noxus?', array['Boram Darkwill', 'Jericho Swain', 'Darius', 'Mordekaiser']),
  (4, 'lore', 'Quem foi o mestre de Zed, líder da Ordem das Sombras?', array['Kusho', 'Shen', 'Kennen', 'Akali']),
  (4, 'lore', 'Em Arcane, como se chama a prisão de Piltover onde Vi é presa?', array['Stillwater', 'Blackgate', 'Ironhold', 'Greywall']),
  (4, 'lore', 'Qual campeão é considerado o último mestre do estilo Wuju?', array['Master Yi', 'Yasuo', 'Irelia', 'Lee Sin']),
  (4, 'lore', 'Como se chama o Darkin que habita a foice de Kayn?', array['Rhaast', 'Aatrox', 'Kai', 'Naafiri']),
  (4, 'lore', 'Qual tribo de Freljord é liderada por Sejuani?', array['Garra do Inverno', 'Avarosanos', 'Guarda do Gelo', 'Dentes de Gelo']),
  (4, 'lore', 'Quem assassinou Gangplank em Águas de Sentina?', array['Miss Fortune', 'Graves', 'Twisted Fate', 'Nautilus']),
  (4, 'lore', 'Quem é o rei de Demacia e pai de Jarvan IV?', array['Jarvan III', 'Garen', 'Jarvan II', 'Galio']),
  (4, 'lore', 'Qual é o sobrenome da família real de Demacia?', array['Lightshield', 'Crownguard', 'Du Couteau', 'Medarda']),
  (4, 'lore', 'Qual campeão aprisionou a alma de Senna em sua lanterna?', array['Thresh', 'Mordekaiser', 'Karthus', 'Hecarim']),
  (4, 'lore', 'Qual foi o primeiro single do grupo virtual True Damage, lançado em 2019?', array['GIANTS', 'POP/STARS', 'THE BADDEST', 'RISE']);
insert into public.site_barao_perguntas (faixa, cat, q, a)
select faixa, cat, q, a from _barao_novas
on conflict (q) do update set faixa = excluded.faixa, cat = excluded.cat, a = excluded.a;
delete from public.site_barao_perguntas where q not in (select q from _barao_novas);
commit;
