// 30 nicks distintos, um personagem de Naruto por bot (ver botsDaily.mjs) —
// nenhum repete, e todos respeitam PLAYER_NAME_PATTERN/MAX_PLAYER_NAME_LENGTH
// (js/data/profile.js): só letras + 1 espaço entre palavras, até 16 chars.
export const NARUTO_NAMES = [
  'Naruto Uzumaki',
  'Sasuke Uchiha',
  'Sakura Haruno',
  'Kakashi Hatake',
  'Itachi Uchiha',
  'Jiraiya',
  'Tsunade',
  'Orochimaru',
  'Gaara',
  'Rock Lee',
  'Neji Hyuga',
  'Hinata Hyuga',
  'Shikamaru Nara',
  'Choji Akimichi',
  'Ino Yamanaka',
  'Kiba Inuzuka',
  'Shino Aburame',
  'Tenten',
  'Might Guy',
  'Minato Namikaze',
  'Kushina Uzumaki',
  'Obito Uchiha',
  'Madara Uchiha',
  'Konan',
  'Nagato',
  'Pain',
  'Kisame Hoshigaki',
  'Deidara',
  'Sasori',
  'Hidan',
];
