-- GERADO por supabase/scripts/gerar_diarios_dados.py: não edite à mão.
-- Respostas do Runetermo e campeões do Campeão Oculto (para o servidor).
-- Como aplicar: cole no SQL Editor do Supabase e clique em Run (depois do 0016).
-- Rodar de novo atualiza a lista; palavras que saíram deixam de ser sorteadas.

begin;
delete from public.site_diario_palavras;
insert into public.site_diario_palavras (chave, palavra, categoria) values
  ('ELISE', 'Elise', 'campeao'),
  ('DARIUS', 'Darius', 'campeao'),
  ('ZHONYA', 'Zhonya', 'item'),
  ('ORIANNA', 'Orianna', 'campeao'),
  ('AURORA', 'Aurora', 'campeao'),
  ('LIANDRY', 'Liandry', 'item'),
  ('GROMP', 'Gromp', 'mapa'),
  ('XAYAH', 'Xayah', 'campeao'),
  ('SINGED', 'Singed', 'campeao'),
  ('DRAVEN', 'Draven', 'campeao'),
  ('NEEKO', 'Neeko', 'campeao'),
  ('POPPY', 'Poppy', 'campeao'),
  ('KSANTE', 'K''Sante', 'campeao'),
  ('MILIO', 'Milio', 'campeao'),
  ('SHOJIN', 'Shojin', 'item'),
  ('SAMIRA', 'Samira', 'campeao'),
  ('AMBESSA', 'Ambessa', 'campeao'),
  ('IRELIA', 'Irelia', 'campeao'),
  ('NILAH', 'Nilah', 'campeao'),
  ('RAKAN', 'Rakan', 'campeao'),
  ('SYNDRA', 'Syndra', 'campeao'),
  ('REKSAI', 'Rek''Sai', 'campeao'),
  ('QUINN', 'Quinn', 'campeao'),
  ('NASUS', 'Nasus', 'campeao'),
  ('KALISTA', 'Kalista', 'campeao'),
  ('GAREN', 'Garen', 'campeao'),
  ('SHURIMA', 'Shurima', 'regiao'),
  ('STERAK', 'Sterak', 'item'),
  ('LILLIA', 'Lillia', 'campeao'),
  ('ALISTAR', 'Alistar', 'campeao'),
  ('JAYCE', 'Jayce', 'campeao'),
  ('KAYLE', 'Kayle', 'campeao'),
  ('KHAZIX', 'Kha''Zix', 'campeao'),
  ('RUMBLE', 'Rumble', 'campeao'),
  ('DEMACIA', 'Demacia', 'regiao'),
  ('IVERN', 'Ivern', 'campeao'),
  ('BRIAR', 'Briar', 'campeao'),
  ('ICATHIA', 'Icathia', 'universo'),
  ('AKSHAN', 'Akshan', 'campeao'),
  ('SOLARI', 'Solari', 'universo'),
  ('VASTAYA', 'Vastaya', 'universo'),
  ('SMOLDER', 'Smolder', 'campeao'),
  ('GRAVES', 'Graves', 'campeao'),
  ('YORDLE', 'Yordle', 'universo'),
  ('AMUMU', 'Amumu', 'campeao'),
  ('LEBLANC', 'LeBlanc', 'campeao'),
  ('LEONA', 'Leona', 'campeao'),
  ('GALIO', 'Galio', 'campeao'),
  ('YOUMUU', 'Youmuu', 'item'),
  ('SHYVANA', 'Shyvana', 'campeao'),
  ('MORGANA', 'Morgana', 'campeao'),
  ('RAMMUS', 'Rammus', 'campeao'),
  ('WARWICK', 'Warwick', 'campeao'),
  ('KOGMAW', 'Kog''Maw', 'campeao'),
  ('SHACO', 'Shaco', 'campeao'),
  ('WARMOG', 'Warmog', 'item'),
  ('TEEMO', 'Teemo', 'campeao'),
  ('RENGAR', 'Rengar', 'campeao'),
  ('ZILEAN', 'Zilean', 'campeao'),
  ('CBLOL', 'CBLOL', 'cenario'),
  ('KRUGS', 'Krugs', 'mapa'),
  ('NOXUS', 'Noxus', 'regiao'),
  ('EZREAL', 'Ezreal', 'campeao'),
  ('SERYLDA', 'Serylda', 'item'),
  ('THRESH', 'Thresh', 'campeao'),
  ('VIEGO', 'Viego', 'campeao'),
  ('SENNA', 'Senna', 'campeao'),
  ('TIAMAT', 'Tiamat', 'item'),
  ('LUCIAN', 'Lucian', 'campeao'),
  ('RENATA', 'Renata', 'campeao'),
  ('YUUMI', 'Yuumi', 'campeao'),
  ('KAISA', 'Kai''Sa', 'campeao'),
  ('RANDUIN', 'Randuin', 'item'),
  ('DIANA', 'Diana', 'campeao'),
  ('CAMILLE', 'Camille', 'campeao'),
  ('KINDRED', 'Kindred', 'campeao'),
  ('IONIA', 'Ionia', 'regiao'),
  ('JARVAN', 'Jarvan', 'campeao'),
  ('WUKONG', 'Wukong', 'campeao'),
  ('NASHOR', 'Nashor', 'mapa'),
  ('NEXUS', 'Nexus', 'mapa'),
  ('ILLAOI', 'Illaoi', 'campeao'),
  ('VEIGAR', 'Veigar', 'campeao'),
  ('ZIGGS', 'Ziggs', 'campeao'),
  ('YORICK', 'Yorick', 'campeao'),
  ('FIORA', 'Fiora', 'campeao'),
  ('LUDEN', 'Luden', 'item'),
  ('QIYANA', 'Qiyana', 'campeao'),
  ('KARTHUS', 'Karthus', 'campeao'),
  ('RABADON', 'Rabadon', 'item'),
  ('HEXTEC', 'Hextec', 'mapa'),
  ('SORAKA', 'Soraka', 'campeao'),
  ('URGOT', 'Urgot', 'campeao'),
  ('GRAGAS', 'Gragas', 'campeao'),
  ('TARGON', 'Targon', 'regiao'),
  ('TALIYAH', 'Taliyah', 'campeao'),
  ('YASUO', 'Yasuo', 'campeao'),
  ('BRAUM', 'Braum', 'campeao'),
  ('RYLAI', 'Rylai', 'item'),
  ('ANNIE', 'Annie', 'campeao'),
  ('ANIVIA', 'Anivia', 'campeao'),
  ('SEJUANI', 'Sejuani', 'campeao'),
  ('VELKOZ', 'Vel''Koz', 'campeao'),
  ('CORKI', 'Corki', 'campeao'),
  ('VARUS', 'Varus', 'campeao'),
  ('KARMA', 'Karma', 'campeao'),
  ('JANNA', 'Janna', 'campeao'),
  ('TWITCH', 'Twitch', 'campeao'),
  ('KINKOU', 'Kinkou', 'universo'),
  ('TALON', 'Talon', 'campeao'),
  ('SYLAS', 'Sylas', 'campeao'),
  ('MAOKAI', 'Maokai', 'campeao'),
  ('AATROX', 'Aatrox', 'campeao'),
  ('CHOGATH', 'Cho''Gath', 'campeao'),
  ('DARKIN', 'Darkin', 'universo'),
  ('SKARNER', 'Skarner', 'campeao'),
  ('BRAND', 'Brand', 'campeao'),
  ('XERATH', 'Xerath', 'campeao'),
  ('TARIC', 'Taric', 'campeao'),
  ('HECARIM', 'Hecarim', 'campeao'),
  ('KENNEN', 'Kennen', 'campeao'),
  ('RIVEN', 'Riven', 'campeao'),
  ('EVELYNN', 'Evelynn', 'campeao'),
  ('AKALI', 'Akali', 'campeao'),
  ('LUNARI', 'Lunari', 'universo'),
  ('BELVETH', 'Bel''Veth', 'campeao'),
  ('CAITLYN', 'Caitlyn', 'campeao'),
  ('SWAIN', 'Swain', 'campeao'),
  ('NIDALEE', 'Nidalee', 'campeao'),
  ('NAAFIRI', 'Naafiri', 'campeao'),
  ('SIVIR', 'Sivir', 'campeao'),
  ('VAYNE', 'Vayne', 'campeao'),
  ('ARCANE', 'Arcane', 'universo'),
  ('TRUNDLE', 'Trundle', 'campeao'),
  ('VIKTOR', 'Viktor', 'campeao'),
  ('IXTAL', 'Ixtal', 'regiao'),
  ('MEJAI', 'Mejai', 'item'),
  ('ATAKHAN', 'Atakhan', 'mapa'),
  ('RAKKOR', 'Rakkor', 'universo'),
  ('SEVIKA', 'Sevika', 'universo'),
  ('BANSHEE', 'Banshee', 'item'),
  ('SILCO', 'Silco', 'universo'),
  ('GUINSOO', 'Guinsoo', 'item'),
  ('HELIA', 'Helia', 'regiao'),
  ('MORELLO', 'Morello', 'item'),
  ('DORAN', 'Doran', 'item'),
  ('MIKAEL', 'Mikael', 'item'),
  ('CAMAVOR', 'Camavor', 'regiao'),
  ('NAVORI', 'Navori', 'item'),
  ('VANDER', 'Vander', 'universo');
delete from public.site_diario_campeoes;
insert into public.site_diario_campeoes (nome, dados) values
  ('Aatrox', '{"ano": 2013, "genero": "M", "regioes": ["Runeterra"], "posicoes": ["Top"], "classes": ["Lutador"], "especies": ["Darkin"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Ahri', '{"ano": 2011, "genero": "F", "regioes": ["Ionia"], "posicoes": ["Mid"], "classes": ["Mago", "Assassino"], "especies": ["Vastaya"], "alcance": ["À distância"]}'::jsonb),
  ('Akali', '{"ano": 2010, "genero": "F", "regioes": ["Ionia"], "posicoes": ["Mid", "Top"], "classes": ["Assassino"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Akshan', '{"ano": 2021, "genero": "M", "regioes": ["Shurima"], "posicoes": ["Mid", "Top"], "classes": ["Atirador", "Assassino"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Alistar', '{"ano": 2009, "genero": "M", "regioes": ["Runeterra"], "posicoes": ["Suporte"], "classes": ["Tanque", "Suporte"], "especies": ["Minotauro"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Ambessa', '{"ano": 2024, "genero": "F", "regioes": ["Noxus"], "posicoes": ["Top"], "classes": ["Lutador", "Assassino"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Amumu', '{"ano": 2009, "genero": "M", "regioes": ["Shurima"], "posicoes": ["Jungle", "Suporte"], "classes": ["Tanque"], "especies": ["Morto-vivo", "Yordle"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Anivia', '{"ano": 2009, "genero": "F", "regioes": ["Freljord"], "posicoes": ["Mid"], "classes": ["Mago"], "especies": ["Semideus"], "alcance": ["À distância"]}'::jsonb),
  ('Annie', '{"ano": 2009, "genero": "F", "regioes": ["Noxus"], "posicoes": ["Mid", "Suporte"], "classes": ["Mago"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Aphelios', '{"ano": 2019, "genero": "M", "regioes": ["Targon"], "posicoes": ["ADC"], "classes": ["Atirador"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Ashe', '{"ano": 2009, "genero": "F", "regioes": ["Freljord"], "posicoes": ["ADC", "Suporte"], "classes": ["Atirador"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Aurelion Sol', '{"ano": 2016, "genero": "M", "regioes": ["Targon"], "posicoes": ["Mid"], "classes": ["Mago"], "especies": ["Dragão", "Celestial"], "alcance": ["À distância"]}'::jsonb),
  ('Aurora', '{"ano": 2024, "genero": "F", "regioes": ["Freljord"], "posicoes": ["Mid", "Top"], "classes": ["Mago"], "especies": ["Vastaya"], "alcance": ["À distância"]}'::jsonb),
  ('Azir', '{"ano": 2014, "genero": "M", "regioes": ["Shurima"], "posicoes": ["Mid"], "classes": ["Mago"], "especies": ["Ascendido"], "alcance": ["À distância"]}'::jsonb),
  ('Bard', '{"ano": 2015, "genero": "M", "regioes": ["Runeterra"], "posicoes": ["Suporte"], "classes": ["Suporte"], "especies": ["Celestial"], "alcance": ["À distância"]}'::jsonb),
  ('Bel''Veth', '{"ano": 2022, "genero": "F", "regioes": ["Vazio"], "posicoes": ["Jungle"], "classes": ["Lutador"], "especies": ["Criatura do Vazio"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Blitzcrank', '{"ano": 2009, "genero": "M", "regioes": ["Zaun"], "posicoes": ["Suporte"], "classes": ["Tanque", "Suporte"], "especies": ["Constructo"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Brand', '{"ano": 2011, "genero": "M", "regioes": ["Runeterra"], "posicoes": ["Suporte", "Mid"], "classes": ["Mago"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Braum', '{"ano": 2014, "genero": "M", "regioes": ["Freljord"], "posicoes": ["Suporte"], "classes": ["Tanque", "Suporte"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Briar', '{"ano": 2023, "genero": "F", "regioes": ["Noxus"], "posicoes": ["Jungle"], "classes": ["Lutador", "Assassino"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Caitlyn', '{"ano": 2011, "genero": "F", "regioes": ["Piltover"], "posicoes": ["ADC"], "classes": ["Atirador"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Camille', '{"ano": 2016, "genero": "F", "regioes": ["Piltover"], "posicoes": ["Top"], "classes": ["Lutador"], "especies": ["Humano", "Ciborgue"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Cassiopeia', '{"ano": 2010, "genero": "F", "regioes": ["Noxus"], "posicoes": ["Mid"], "classes": ["Mago"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Cho''Gath', '{"ano": 2009, "genero": "M", "regioes": ["Vazio"], "posicoes": ["Top"], "classes": ["Tanque"], "especies": ["Criatura do Vazio"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Corki', '{"ano": 2009, "genero": "M", "regioes": ["Bandópolis"], "posicoes": ["Mid"], "classes": ["Atirador"], "especies": ["Yordle"], "alcance": ["À distância"]}'::jsonb),
  ('Darius', '{"ano": 2012, "genero": "M", "regioes": ["Noxus"], "posicoes": ["Top"], "classes": ["Lutador"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Diana', '{"ano": 2012, "genero": "F", "regioes": ["Targon"], "posicoes": ["Jungle", "Mid"], "classes": ["Lutador", "Assassino"], "especies": ["Humano", "Celestial"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Dr. Mundo', '{"ano": 2009, "genero": "M", "regioes": ["Zaun"], "posicoes": ["Top", "Jungle"], "classes": ["Tanque"], "especies": ["Humano", "Quimtec"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Draven', '{"ano": 2012, "genero": "M", "regioes": ["Noxus"], "posicoes": ["ADC"], "classes": ["Atirador"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Ekko', '{"ano": 2015, "genero": "M", "regioes": ["Zaun"], "posicoes": ["Jungle", "Mid"], "classes": ["Assassino"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Elise', '{"ano": 2012, "genero": "F", "regioes": ["Ilhas das Sombras"], "posicoes": ["Jungle"], "classes": ["Mago"], "especies": ["Humano"], "alcance": ["Corpo a corpo", "À distância"]}'::jsonb),
  ('Evelynn', '{"ano": 2009, "genero": "F", "regioes": ["Runeterra"], "posicoes": ["Jungle"], "classes": ["Assassino"], "especies": ["Demônio"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Ezreal', '{"ano": 2010, "genero": "M", "regioes": ["Piltover"], "posicoes": ["ADC"], "classes": ["Atirador"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Fiddlesticks', '{"ano": 2009, "genero": "Outro", "regioes": ["Runeterra"], "posicoes": ["Jungle"], "classes": ["Mago"], "especies": ["Demônio"], "alcance": ["À distância"]}'::jsonb),
  ('Fiora', '{"ano": 2012, "genero": "F", "regioes": ["Demacia"], "posicoes": ["Top"], "classes": ["Lutador"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Fizz', '{"ano": 2011, "genero": "M", "regioes": ["Bilgewater"], "posicoes": ["Mid"], "classes": ["Assassino"], "especies": ["Yordle"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Galio', '{"ano": 2010, "genero": "M", "regioes": ["Demacia"], "posicoes": ["Mid", "Suporte"], "classes": ["Tanque"], "especies": ["Constructo"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Gangplank', '{"ano": 2009, "genero": "M", "regioes": ["Bilgewater"], "posicoes": ["Top"], "classes": ["Lutador"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Garen', '{"ano": 2010, "genero": "M", "regioes": ["Demacia"], "posicoes": ["Top"], "classes": ["Lutador"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Gnar', '{"ano": 2014, "genero": "M", "regioes": ["Freljord"], "posicoes": ["Top"], "classes": ["Lutador"], "especies": ["Yordle"], "alcance": ["Corpo a corpo", "À distância"]}'::jsonb),
  ('Gragas', '{"ano": 2010, "genero": "M", "regioes": ["Freljord"], "posicoes": ["Jungle", "Top"], "classes": ["Lutador"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Graves', '{"ano": 2011, "genero": "M", "regioes": ["Bilgewater"], "posicoes": ["Jungle"], "classes": ["Atirador"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Gwen', '{"ano": 2021, "genero": "F", "regioes": ["Ilhas das Sombras"], "posicoes": ["Top", "Jungle"], "classes": ["Lutador"], "especies": ["Espírito"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Hecarim', '{"ano": 2012, "genero": "M", "regioes": ["Ilhas das Sombras"], "posicoes": ["Jungle"], "classes": ["Lutador"], "especies": ["Morto-vivo"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Heimerdinger', '{"ano": 2009, "genero": "M", "regioes": ["Piltover"], "posicoes": ["Mid", "Suporte"], "classes": ["Mago"], "especies": ["Yordle"], "alcance": ["À distância"]}'::jsonb),
  ('Hwei', '{"ano": 2023, "genero": "M", "regioes": ["Ionia"], "posicoes": ["Mid", "Suporte"], "classes": ["Mago"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Illaoi', '{"ano": 2015, "genero": "F", "regioes": ["Bilgewater"], "posicoes": ["Top"], "classes": ["Lutador"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Irelia', '{"ano": 2010, "genero": "F", "regioes": ["Ionia"], "posicoes": ["Top", "Mid"], "classes": ["Lutador"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Ivern', '{"ano": 2016, "genero": "M", "regioes": ["Ionia"], "posicoes": ["Jungle"], "classes": ["Suporte"], "especies": ["Espírito"], "alcance": ["À distância"]}'::jsonb),
  ('Janna', '{"ano": 2009, "genero": "F", "regioes": ["Zaun"], "posicoes": ["Suporte"], "classes": ["Suporte"], "especies": ["Espírito"], "alcance": ["À distância"]}'::jsonb),
  ('Jarvan IV', '{"ano": 2011, "genero": "M", "regioes": ["Demacia"], "posicoes": ["Jungle"], "classes": ["Lutador", "Tanque"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Jax', '{"ano": 2009, "genero": "M", "regioes": ["Runeterra"], "posicoes": ["Top", "Jungle"], "classes": ["Lutador"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Jayce', '{"ano": 2012, "genero": "M", "regioes": ["Piltover"], "posicoes": ["Top", "Mid"], "classes": ["Lutador"], "especies": ["Humano"], "alcance": ["Corpo a corpo", "À distância"]}'::jsonb),
  ('Jhin', '{"ano": 2016, "genero": "M", "regioes": ["Ionia"], "posicoes": ["ADC"], "classes": ["Atirador"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Jinx', '{"ano": 2013, "genero": "F", "regioes": ["Zaun"], "posicoes": ["ADC"], "classes": ["Atirador"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('K''Sante', '{"ano": 2022, "genero": "M", "regioes": ["Shurima"], "posicoes": ["Top"], "classes": ["Tanque", "Lutador"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Kai''Sa', '{"ano": 2018, "genero": "F", "regioes": ["Vazio"], "posicoes": ["ADC"], "classes": ["Atirador"], "especies": ["Humano", "Criatura do Vazio"], "alcance": ["À distância"]}'::jsonb),
  ('Kalista', '{"ano": 2014, "genero": "F", "regioes": ["Ilhas das Sombras"], "posicoes": ["ADC"], "classes": ["Atirador"], "especies": ["Morto-vivo"], "alcance": ["À distância"]}'::jsonb),
  ('Karma', '{"ano": 2011, "genero": "F", "regioes": ["Ionia"], "posicoes": ["Suporte", "Mid"], "classes": ["Mago", "Suporte"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Karthus', '{"ano": 2009, "genero": "M", "regioes": ["Ilhas das Sombras"], "posicoes": ["Jungle"], "classes": ["Mago"], "especies": ["Morto-vivo"], "alcance": ["À distância"]}'::jsonb),
  ('Kassadin', '{"ano": 2009, "genero": "M", "regioes": ["Vazio"], "posicoes": ["Mid"], "classes": ["Assassino"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Katarina', '{"ano": 2009, "genero": "F", "regioes": ["Noxus"], "posicoes": ["Mid"], "classes": ["Assassino"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Kayle', '{"ano": 2009, "genero": "F", "regioes": ["Demacia"], "posicoes": ["Top"], "classes": ["Lutador", "Mago"], "especies": ["Celestial"], "alcance": ["Corpo a corpo", "À distância"]}'::jsonb),
  ('Kayn', '{"ano": 2017, "genero": "M", "regioes": ["Ionia"], "posicoes": ["Jungle"], "classes": ["Lutador", "Assassino"], "especies": ["Humano", "Darkin"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Kennen', '{"ano": 2010, "genero": "M", "regioes": ["Ionia"], "posicoes": ["Top"], "classes": ["Mago"], "especies": ["Yordle"], "alcance": ["À distância"]}'::jsonb),
  ('Kha''Zix', '{"ano": 2012, "genero": "M", "regioes": ["Vazio"], "posicoes": ["Jungle"], "classes": ["Assassino"], "especies": ["Criatura do Vazio"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Kindred', '{"ano": 2015, "genero": "Outro", "regioes": ["Runeterra"], "posicoes": ["Jungle"], "classes": ["Atirador"], "especies": ["Espírito"], "alcance": ["À distância"]}'::jsonb),
  ('Kled', '{"ano": 2016, "genero": "M", "regioes": ["Noxus"], "posicoes": ["Top"], "classes": ["Lutador"], "especies": ["Yordle"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Kog''Maw', '{"ano": 2010, "genero": "M", "regioes": ["Vazio"], "posicoes": ["ADC"], "classes": ["Atirador"], "especies": ["Criatura do Vazio"], "alcance": ["À distância"]}'::jsonb),
  ('LeBlanc', '{"ano": 2010, "genero": "F", "regioes": ["Noxus"], "posicoes": ["Mid"], "classes": ["Assassino", "Mago"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Lee Sin', '{"ano": 2011, "genero": "M", "regioes": ["Ionia"], "posicoes": ["Jungle"], "classes": ["Lutador"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Leona', '{"ano": 2011, "genero": "F", "regioes": ["Targon"], "posicoes": ["Suporte"], "classes": ["Tanque", "Suporte"], "especies": ["Humano", "Celestial"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Lillia', '{"ano": 2020, "genero": "F", "regioes": ["Ionia"], "posicoes": ["Jungle"], "classes": ["Lutador", "Mago"], "especies": ["Espírito"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Lissandra', '{"ano": 2013, "genero": "F", "regioes": ["Freljord"], "posicoes": ["Mid"], "classes": ["Mago"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Locke', '{"ano": 2026, "genero": "M", "regioes": ["Demacia"], "posicoes": ["Mid"], "classes": ["Assassino"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Lucian', '{"ano": 2013, "genero": "M", "regioes": ["Runeterra"], "posicoes": ["ADC", "Mid"], "classes": ["Atirador"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Lulu', '{"ano": 2012, "genero": "F", "regioes": ["Bandópolis"], "posicoes": ["Suporte"], "classes": ["Suporte", "Mago"], "especies": ["Yordle"], "alcance": ["À distância"]}'::jsonb),
  ('Lux', '{"ano": 2010, "genero": "F", "regioes": ["Demacia"], "posicoes": ["Suporte", "Mid"], "classes": ["Mago"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Malphite', '{"ano": 2009, "genero": "M", "regioes": ["Ixtal"], "posicoes": ["Top"], "classes": ["Tanque"], "especies": ["Elemental"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Malzahar', '{"ano": 2010, "genero": "M", "regioes": ["Vazio"], "posicoes": ["Mid"], "classes": ["Mago"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Maokai', '{"ano": 2011, "genero": "M", "regioes": ["Ilhas das Sombras"], "posicoes": ["Suporte", "Jungle"], "classes": ["Tanque"], "especies": ["Espírito"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Master Yi', '{"ano": 2009, "genero": "M", "regioes": ["Ionia"], "posicoes": ["Jungle"], "classes": ["Assassino", "Lutador"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Mel', '{"ano": 2025, "genero": "F", "regioes": ["Noxus"], "posicoes": ["Mid", "Suporte"], "classes": ["Mago"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Milio', '{"ano": 2023, "genero": "M", "regioes": ["Ixtal"], "posicoes": ["Suporte"], "classes": ["Suporte"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Miss Fortune', '{"ano": 2010, "genero": "F", "regioes": ["Bilgewater"], "posicoes": ["ADC"], "classes": ["Atirador"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Mordekaiser', '{"ano": 2010, "genero": "M", "regioes": ["Noxus"], "posicoes": ["Top"], "classes": ["Lutador"], "especies": ["Morto-vivo"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Morgana', '{"ano": 2009, "genero": "F", "regioes": ["Demacia"], "posicoes": ["Suporte"], "classes": ["Mago", "Suporte"], "especies": ["Celestial"], "alcance": ["À distância"]}'::jsonb),
  ('Naafiri', '{"ano": 2023, "genero": "F", "regioes": ["Shurima"], "posicoes": ["Mid"], "classes": ["Assassino"], "especies": ["Darkin"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Nami', '{"ano": 2012, "genero": "F", "regioes": ["Runeterra"], "posicoes": ["Suporte"], "classes": ["Suporte"], "especies": ["Vastaya"], "alcance": ["À distância"]}'::jsonb),
  ('Nasus', '{"ano": 2009, "genero": "M", "regioes": ["Shurima"], "posicoes": ["Top"], "classes": ["Lutador"], "especies": ["Ascendido"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Nautilus', '{"ano": 2012, "genero": "M", "regioes": ["Bilgewater"], "posicoes": ["Suporte"], "classes": ["Tanque"], "especies": ["Morto-vivo"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Neeko', '{"ano": 2018, "genero": "F", "regioes": ["Ixtal"], "posicoes": ["Mid", "Suporte"], "classes": ["Mago"], "especies": ["Vastaya"], "alcance": ["À distância"]}'::jsonb),
  ('Nidalee', '{"ano": 2009, "genero": "F", "regioes": ["Ixtal"], "posicoes": ["Jungle"], "classes": ["Assassino"], "especies": ["Humano"], "alcance": ["Corpo a corpo", "À distância"]}'::jsonb),
  ('Nilah', '{"ano": 2022, "genero": "F", "regioes": ["Runeterra"], "posicoes": ["ADC"], "classes": ["Lutador"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Nocturne', '{"ano": 2011, "genero": "M", "regioes": ["Runeterra"], "posicoes": ["Jungle"], "classes": ["Assassino"], "especies": ["Demônio"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Nunu e Willump', '{"ano": 2009, "genero": "M", "regioes": ["Freljord"], "posicoes": ["Jungle"], "classes": ["Tanque"], "especies": ["Humano", "Yeti"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Olaf', '{"ano": 2010, "genero": "M", "regioes": ["Freljord"], "posicoes": ["Top", "Jungle"], "classes": ["Lutador"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Orianna', '{"ano": 2011, "genero": "F", "regioes": ["Piltover"], "posicoes": ["Mid"], "classes": ["Mago"], "especies": ["Constructo"], "alcance": ["À distância"]}'::jsonb),
  ('Ornn', '{"ano": 2017, "genero": "M", "regioes": ["Freljord"], "posicoes": ["Top"], "classes": ["Tanque"], "especies": ["Semideus"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Pantheon', '{"ano": 2010, "genero": "M", "regioes": ["Targon"], "posicoes": ["Top", "Mid", "Suporte"], "classes": ["Lutador", "Assassino"], "especies": ["Humano", "Celestial"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Poppy', '{"ano": 2010, "genero": "F", "regioes": ["Demacia"], "posicoes": ["Top", "Jungle"], "classes": ["Tanque"], "especies": ["Yordle"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Pyke', '{"ano": 2018, "genero": "M", "regioes": ["Bilgewater"], "posicoes": ["Suporte"], "classes": ["Assassino"], "especies": ["Morto-vivo"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Qiyana', '{"ano": 2019, "genero": "F", "regioes": ["Ixtal"], "posicoes": ["Mid"], "classes": ["Assassino"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Quinn', '{"ano": 2013, "genero": "F", "regioes": ["Demacia"], "posicoes": ["Top"], "classes": ["Atirador"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Rakan', '{"ano": 2017, "genero": "M", "regioes": ["Ionia"], "posicoes": ["Suporte"], "classes": ["Suporte"], "especies": ["Vastaya"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Rammus', '{"ano": 2009, "genero": "M", "regioes": ["Shurima"], "posicoes": ["Jungle"], "classes": ["Tanque"], "especies": ["Animal"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Rek''Sai', '{"ano": 2014, "genero": "F", "regioes": ["Vazio"], "posicoes": ["Jungle"], "classes": ["Lutador"], "especies": ["Criatura do Vazio"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Rell', '{"ano": 2020, "genero": "F", "regioes": ["Noxus"], "posicoes": ["Suporte"], "classes": ["Tanque"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Renata Glasc', '{"ano": 2022, "genero": "F", "regioes": ["Zaun"], "posicoes": ["Suporte"], "classes": ["Suporte"], "especies": ["Humano", "Quimtec"], "alcance": ["À distância"]}'::jsonb),
  ('Renekton', '{"ano": 2011, "genero": "M", "regioes": ["Shurima"], "posicoes": ["Top"], "classes": ["Lutador"], "especies": ["Ascendido"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Rengar', '{"ano": 2012, "genero": "M", "regioes": ["Ixtal"], "posicoes": ["Jungle", "Top"], "classes": ["Assassino"], "especies": ["Vastaya"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Riven', '{"ano": 2011, "genero": "F", "regioes": ["Noxus"], "posicoes": ["Top"], "classes": ["Lutador"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Rumble', '{"ano": 2011, "genero": "M", "regioes": ["Bandópolis"], "posicoes": ["Top", "Mid"], "classes": ["Lutador", "Mago"], "especies": ["Yordle"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Ryze', '{"ano": 2009, "genero": "M", "regioes": ["Runeterra"], "posicoes": ["Mid", "Top"], "classes": ["Mago"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Samira', '{"ano": 2020, "genero": "F", "regioes": ["Noxus"], "posicoes": ["ADC"], "classes": ["Atirador"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Sejuani', '{"ano": 2012, "genero": "F", "regioes": ["Freljord"], "posicoes": ["Jungle"], "classes": ["Tanque"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Senna', '{"ano": 2019, "genero": "F", "regioes": ["Runeterra"], "posicoes": ["Suporte", "ADC"], "classes": ["Atirador", "Suporte"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Seraphine', '{"ano": 2020, "genero": "F", "regioes": ["Piltover"], "posicoes": ["Suporte", "Mid"], "classes": ["Mago", "Suporte"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Sett', '{"ano": 2020, "genero": "M", "regioes": ["Ionia"], "posicoes": ["Top", "Suporte"], "classes": ["Lutador", "Tanque"], "especies": ["Vastaya"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Shaco', '{"ano": 2009, "genero": "M", "regioes": ["Runeterra"], "posicoes": ["Jungle", "Suporte"], "classes": ["Assassino"], "especies": ["Demônio"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Shen', '{"ano": 2010, "genero": "M", "regioes": ["Ionia"], "posicoes": ["Top"], "classes": ["Tanque"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Shyvana', '{"ano": 2011, "genero": "F", "regioes": ["Demacia"], "posicoes": ["Jungle"], "classes": ["Lutador"], "especies": ["Dragão", "Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Singed', '{"ano": 2009, "genero": "M", "regioes": ["Zaun"], "posicoes": ["Top"], "classes": ["Tanque"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Sion', '{"ano": 2009, "genero": "M", "regioes": ["Noxus"], "posicoes": ["Top"], "classes": ["Tanque"], "especies": ["Morto-vivo"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Sivir', '{"ano": 2009, "genero": "F", "regioes": ["Shurima"], "posicoes": ["ADC"], "classes": ["Atirador"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Skarner', '{"ano": 2011, "genero": "M", "regioes": ["Ixtal"], "posicoes": ["Jungle", "Top"], "classes": ["Tanque"], "especies": ["Brackern"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Smolder', '{"ano": 2024, "genero": "M", "regioes": ["Runeterra"], "posicoes": ["ADC"], "classes": ["Atirador"], "especies": ["Dragão"], "alcance": ["À distância"]}'::jsonb),
  ('Sona', '{"ano": 2010, "genero": "F", "regioes": ["Demacia"], "posicoes": ["Suporte"], "classes": ["Suporte", "Mago"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Soraka', '{"ano": 2009, "genero": "F", "regioes": ["Targon"], "posicoes": ["Suporte"], "classes": ["Suporte"], "especies": ["Celestial"], "alcance": ["À distância"]}'::jsonb),
  ('Swain', '{"ano": 2010, "genero": "M", "regioes": ["Noxus"], "posicoes": ["Suporte", "Mid"], "classes": ["Mago"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Sylas', '{"ano": 2019, "genero": "M", "regioes": ["Demacia"], "posicoes": ["Mid", "Jungle"], "classes": ["Mago", "Assassino"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Syndra', '{"ano": 2012, "genero": "F", "regioes": ["Ionia"], "posicoes": ["Mid"], "classes": ["Mago"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Tahm Kench', '{"ano": 2015, "genero": "M", "regioes": ["Bilgewater"], "posicoes": ["Top", "Suporte"], "classes": ["Tanque"], "especies": ["Demônio"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Taliyah', '{"ano": 2016, "genero": "F", "regioes": ["Shurima"], "posicoes": ["Jungle", "Mid"], "classes": ["Mago"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Talon', '{"ano": 2011, "genero": "M", "regioes": ["Noxus"], "posicoes": ["Mid", "Jungle"], "classes": ["Assassino"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Taric', '{"ano": 2009, "genero": "M", "regioes": ["Targon"], "posicoes": ["Suporte"], "classes": ["Suporte", "Tanque"], "especies": ["Humano", "Celestial"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Teemo', '{"ano": 2009, "genero": "M", "regioes": ["Bandópolis"], "posicoes": ["Top"], "classes": ["Atirador"], "especies": ["Yordle"], "alcance": ["À distância"]}'::jsonb),
  ('Thresh', '{"ano": 2013, "genero": "M", "regioes": ["Ilhas das Sombras"], "posicoes": ["Suporte"], "classes": ["Suporte", "Tanque"], "especies": ["Morto-vivo"], "alcance": ["À distância"]}'::jsonb),
  ('Tristana', '{"ano": 2009, "genero": "F", "regioes": ["Bandópolis"], "posicoes": ["ADC", "Mid"], "classes": ["Atirador"], "especies": ["Yordle"], "alcance": ["À distância"]}'::jsonb),
  ('Trundle', '{"ano": 2010, "genero": "M", "regioes": ["Freljord"], "posicoes": ["Jungle", "Top"], "classes": ["Lutador"], "especies": ["Troll"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Tryndamere', '{"ano": 2009, "genero": "M", "regioes": ["Freljord"], "posicoes": ["Top"], "classes": ["Lutador"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Twisted Fate', '{"ano": 2009, "genero": "M", "regioes": ["Bilgewater"], "posicoes": ["Mid"], "classes": ["Mago"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Twitch', '{"ano": 2009, "genero": "M", "regioes": ["Zaun"], "posicoes": ["ADC"], "classes": ["Atirador"], "especies": ["Animal", "Quimtec"], "alcance": ["À distância"]}'::jsonb),
  ('Udyr', '{"ano": 2009, "genero": "M", "regioes": ["Freljord"], "posicoes": ["Jungle"], "classes": ["Lutador", "Tanque"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Urgot', '{"ano": 2010, "genero": "M", "regioes": ["Zaun"], "posicoes": ["Top"], "classes": ["Lutador"], "especies": ["Humano", "Ciborgue"], "alcance": ["À distância"]}'::jsonb),
  ('Varus', '{"ano": 2012, "genero": "M", "regioes": ["Ionia"], "posicoes": ["ADC", "Mid"], "classes": ["Atirador"], "especies": ["Darkin"], "alcance": ["À distância"]}'::jsonb),
  ('Vayne', '{"ano": 2011, "genero": "F", "regioes": ["Demacia"], "posicoes": ["ADC", "Top"], "classes": ["Atirador"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Veigar', '{"ano": 2009, "genero": "M", "regioes": ["Bandópolis"], "posicoes": ["Mid"], "classes": ["Mago"], "especies": ["Yordle"], "alcance": ["À distância"]}'::jsonb),
  ('Vel''Koz', '{"ano": 2014, "genero": "Outro", "regioes": ["Vazio"], "posicoes": ["Suporte", "Mid"], "classes": ["Mago"], "especies": ["Criatura do Vazio"], "alcance": ["À distância"]}'::jsonb),
  ('Vex', '{"ano": 2021, "genero": "F", "regioes": ["Ilhas das Sombras"], "posicoes": ["Mid"], "classes": ["Mago"], "especies": ["Yordle"], "alcance": ["À distância"]}'::jsonb),
  ('Vi', '{"ano": 2012, "genero": "F", "regioes": ["Piltover"], "posicoes": ["Jungle"], "classes": ["Lutador"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Viego', '{"ano": 2021, "genero": "M", "regioes": ["Ilhas das Sombras"], "posicoes": ["Jungle"], "classes": ["Assassino", "Lutador"], "especies": ["Morto-vivo"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Viktor', '{"ano": 2011, "genero": "M", "regioes": ["Zaun"], "posicoes": ["Mid"], "classes": ["Mago"], "especies": ["Humano", "Ciborgue"], "alcance": ["À distância"]}'::jsonb),
  ('Vladimir', '{"ano": 2010, "genero": "M", "regioes": ["Noxus"], "posicoes": ["Mid", "Top"], "classes": ["Mago"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Volibear', '{"ano": 2011, "genero": "M", "regioes": ["Freljord"], "posicoes": ["Top", "Jungle"], "classes": ["Lutador", "Tanque"], "especies": ["Semideus"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Warwick', '{"ano": 2009, "genero": "M", "regioes": ["Zaun"], "posicoes": ["Jungle", "Top"], "classes": ["Lutador"], "especies": ["Humano", "Quimtec"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Wukong', '{"ano": 2011, "genero": "M", "regioes": ["Ionia"], "posicoes": ["Top", "Jungle"], "classes": ["Lutador"], "especies": ["Vastaya"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Xayah', '{"ano": 2017, "genero": "F", "regioes": ["Ionia"], "posicoes": ["ADC"], "classes": ["Atirador"], "especies": ["Vastaya"], "alcance": ["À distância"]}'::jsonb),
  ('Xerath', '{"ano": 2011, "genero": "M", "regioes": ["Shurima"], "posicoes": ["Suporte", "Mid"], "classes": ["Mago"], "especies": ["Ascendido"], "alcance": ["À distância"]}'::jsonb),
  ('Xin Zhao', '{"ano": 2010, "genero": "M", "regioes": ["Demacia"], "posicoes": ["Jungle"], "classes": ["Lutador"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Yasuo', '{"ano": 2013, "genero": "M", "regioes": ["Ionia"], "posicoes": ["Mid", "Top"], "classes": ["Lutador"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Yone', '{"ano": 2020, "genero": "M", "regioes": ["Ionia"], "posicoes": ["Mid", "Top"], "classes": ["Assassino", "Lutador"], "especies": ["Humano", "Espírito"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Yorick', '{"ano": 2011, "genero": "M", "regioes": ["Ilhas das Sombras"], "posicoes": ["Top"], "classes": ["Lutador"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Yunara', '{"ano": 2025, "genero": "F", "regioes": ["Ionia"], "posicoes": ["ADC"], "classes": ["Atirador"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Yuumi', '{"ano": 2019, "genero": "F", "regioes": ["Bandópolis"], "posicoes": ["Suporte"], "classes": ["Suporte"], "especies": ["Animal"], "alcance": ["À distância"]}'::jsonb),
  ('Zaahen', '{"ano": 2025, "genero": "M", "regioes": ["Runeterra"], "posicoes": ["Top"], "classes": ["Lutador"], "especies": ["Darkin"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Zac', '{"ano": 2013, "genero": "M", "regioes": ["Zaun"], "posicoes": ["Jungle"], "classes": ["Tanque"], "especies": ["Quimtec"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Zed', '{"ano": 2012, "genero": "M", "regioes": ["Ionia"], "posicoes": ["Mid"], "classes": ["Assassino"], "especies": ["Humano"], "alcance": ["Corpo a corpo"]}'::jsonb),
  ('Zeri', '{"ano": 2022, "genero": "F", "regioes": ["Zaun"], "posicoes": ["ADC"], "classes": ["Atirador"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Ziggs', '{"ano": 2012, "genero": "M", "regioes": ["Zaun"], "posicoes": ["Mid", "ADC"], "classes": ["Mago"], "especies": ["Yordle"], "alcance": ["À distância"]}'::jsonb),
  ('Zilean', '{"ano": 2009, "genero": "M", "regioes": ["Runeterra"], "posicoes": ["Suporte"], "classes": ["Suporte", "Mago"], "especies": ["Humano"], "alcance": ["À distância"]}'::jsonb),
  ('Zoe', '{"ano": 2017, "genero": "F", "regioes": ["Targon"], "posicoes": ["Mid"], "classes": ["Mago"], "especies": ["Celestial"], "alcance": ["À distância"]}'::jsonb),
  ('Zyra', '{"ano": 2012, "genero": "F", "regioes": ["Ixtal"], "posicoes": ["Suporte"], "classes": ["Mago"], "especies": ["Planta"], "alcance": ["À distância"]}'::jsonb);
commit;
