-- Alturas da Escala de Runeterra (gerado por jogos/escala/scripts/sql_alturas.py
-- a partir de jogos/escala/dados/itens.json). Pode rodar de novo sem problema.
begin;
delete from public.site_escala_itens;
insert into public.site_escala_itens (id, nome, altura) values
  ('yuumi', 'Yuumi', 0.2),
  ('gnar', 'Gnar (mini)', 0.73),
  ('ziggs', 'Ziggs', 0.76),
  ('kennen', 'Kennen', 0.78),
  ('tristana', 'Tristana', 0.81),
  ('teemo', 'Teemo', 0.81),
  ('fizz', 'Fizz', 0.91),
  ('rammus', 'Rammus', 0.91),
  ('poppy', 'Poppy', 0.96),
  ('amumu', 'Amumu', 1.09),
  ('annie', 'Annie', 1.27),
  ('zoe', 'Zoe', 1.44),
  ('neeko', 'Neeko', 1.44),
  ('akali', 'Akali', 1.6),
  ('jinx', 'Jinx', 1.6),
  ('xayah', 'Xayah', 1.6),
  ('katarina', 'Katarina', 1.65),
  ('yasuo', 'Yasuo', 1.67),
  ('missfortune', 'Miss Fortune', 1.67),
  ('leesin', 'Lee Sin', 1.67),
  ('ezreal', 'Ezreal', 1.72),
  ('ashe', 'Ashe', 1.75),
  ('ekko', 'Ekko', 1.75),
  ('vayne', 'Vayne', 1.75),
  ('lux', 'Lux', 1.77),
  ('zed', 'Zed', 1.77),
  ('riven', 'Riven', 1.8),
  ('vi', 'Vi', 1.8),
  ('masteryi', 'Master Yi', 1.8),
  ('gangplank', 'Gangplank', 1.82),
  ('jayce', 'Jayce', 1.82),
  ('tryndamere', 'Tryndamere', 1.85),
  ('twistedfate', 'Twisted Fate', 1.85),
  ('jax', 'Jax', 1.87),
  ('viktor', 'Viktor', 1.87),
  ('jarvaniv', 'Jarvan IV', 1.9),
  ('jhin', 'Jhin', 1.93),
  ('pyke', 'Pyke', 1.93),
  ('darius', 'Darius', 1.95),
  ('garen', 'Garen', 1.95),
  ('illaoi', 'Illaoi', 1.95),
  ('rengar', 'Rengar', 2.03),
  ('camille', 'Camille', 2.08),
  ('gragas', 'Gragas', 2.18),
  ('braum', 'Braum', 2.26),
  ('warwick', 'Warwick', 2.33),
  ('thresh', 'Thresh', 2.43),
  ('azir', 'Azir', 2.56),
  ('drmundo', 'Dr. Mundo', 2.64),
  ('blitzcrank', 'Blitzcrank', 2.74),
  ('nunu', 'Nunu e Willump', 2.74),
  ('sion', 'Sion', 2.74),
  ('ivern', 'Ivern', 3.04),
  ('urgot', 'Urgot', 3.04),
  ('mordekaiser', 'Mordekaiser', 3.66),
  ('renekton', 'Renekton', 4.57),
  ('nasus', 'Nasus', 4.57),
  ('trundle', 'Trundle', 4.57),
  ('maokai', 'Maokai', 6.7),
  ('aatrox', 'Aatrox', 6.78),
  ('velkoz', 'Vel''Koz', 9.14),
  ('nautilus', 'Nautilus', 12.0),
  ('chogath', 'Cho''Gath', 21.9),
  ('galio', 'Galio', 48.8),
  ('volibear', 'Volibear', 81.0),
  ('ornn', 'Ornn', 81.0),
  ('malphite', 'Malphite', 103.6),
  ('baron', 'Barão Na''Shor', 15.0),
  ('riftherald', 'Arauto do Vale', 2.8),
  ('dragon_fire', 'Dragão elemental', 4.6),
  ('dragon_elder', 'Dragão Ancião', 8.0),
  ('atakhan', 'Atakhan', 6.8),
  ('turret', 'Torre', 9.0),
  ('inhibitor', 'Inibidor', 3.0),
  ('nexus', 'Nexus', 7.5),
  ('tropa-melee', 'Tropa corpo a corpo', 0.9),
  ('gromp', 'Gromp', 1.48),
  ('crab', 'Aronguejo', 1.1),
  ('blue', 'Sentinela Azul', 2.9),
  ('red', 'Rubrivira', 2.4),
  ('krug', 'Krug Ancião', 2.08),
  ('razorbeak', 'Navalhante', 1.36),
  ('murkwolf', 'Lobo Sombrio', 0.9),
  ('poro', 'Poro', 0.4),
  ('sightward', 'Sentinela (ward)', 0.6),
  ('bastao-grande', 'Bastão Desnecessariamente Grande', 3.8),
  ('lamina-rei-destruido', 'Lâmina do Rei Destruído', 1.95),
  ('martelo-jayce', 'Martelo do Jayce', 2.2),
  ('manoplas-vi', 'Manoplas da Vi', 0.9);
commit;
